#Requires AutoHotkey >=2.0

A_MenuMaskKey := "vkE8"
InstallKeybdHook
SendMode("Event")
SetKeyDelay(0)
SetWorkingDir(A_ScriptDir)
#SingleInstance force
#HotString c * ?
#UseHook true

/***********
 * HOTKEYS *
 ***********/

#InputLevel 2

; Default RAlt Disabler
~RAlt::
~<!RAlt::
~>!LAlt::Send("{Blind}{vkE8}")

; Non-Diacritics
>!Space::
<^>!Space::Send("​")
>![::
<^>![::Send("⁅")
>!]::
<^>!]::Send("⁆")
>!.::
<^>!.::Send("·")
>!;::
<^>!;::Hotstring("Reset")

; Disabled Hotkeys
>!B::
<^>!B::return
>!H::
<^>!H::return
>!Y::
<^>!Y::return

; Main Diacritics (RAlt + Key)
>!A::
<^>!A::Send("́")
>!Q::
<^>!Q::Send("̋")
>!G::
<^>!G::Send("̀")
>!T::
<^>!T::Send("̏")
>!F::
<^>!F::Send("̂")
>!V::
<^>!V::Send("̌")
>!S::
<^>!S::Send("̵")
>!W::
<^>!W::Send("̷")
>!M::
<^>!M::Send("̄")
>!K::
<^>!K::Send("̅")
>!U::
<^>!U::Send("̆")
>!I::
<^>!I::Send("̑")
>!E::
<^>!E::Send("̈")
>!D::
<^>!D::Send("̇")
>!R::
<^>!R::Send("̊")
>!N::
<^>!N::Send("̃")
>!O::
<^>!O::Send("̨")
>!Z::
<^>!Z::Send("̧")
>!C::
<^>!C::Send("̦")
>!X::
<^>!X::Send("̽")
>!L::
<^>!L::Send("̍")
>!P::
<^>!P::Send("̎")
>!J::
<^>!J::Send("̡")

; Side Diacritics (RAlt + LAlt + Key)
<!>!A::
<^<!>!A::Send("̗")
<!>!G::
<^<!>!G::Send("̖")
<!>!F::
<^<!>!F::Send("̭")
<!>!V::
<^<!>!V::Send("̬")
<!>!S::
<^<!>!S::Send("̶")
<!>!W::
<^<!>!W::Send("̸")
<!>!M::
<^<!>!M::Send("̱")
<!>!K::
<^<!>!K::Send("̲")
<!>!U::
<^<!>!U::Send("̮")
<!>!I::
<^<!>!I::Send("̯")
<!>!E::
<^<!>!E::Send("̤")
<!>!D::
<^<!>!D::Send("̣")
<!>!R::
<^<!>!R::Send("̥")
<!>!N::
<^<!>!N::Send("̰")
<!>!O::
<^<!>!O::Send("᷎")
<!>!Z::
<^<!>!Z::Send("̉")
<!>!C::
<^<!>!C::Send("̛")
<!>!X::
<^<!>!X::Send("͓")
<!>!L::
<^<!>!L::Send("̩")
<!>!P::
<^<!>!P::Send("͈")
<!>!J::
<^<!>!J::Send("̢")

/***********************
 * DIACRITIC COMBINERS *
 ***********************/

#InputLevel 1

; Acute
:x:Á::Send("Á")
:x:á::Send("á")
:x:Ć::Send("Ć")
:x:ć::Send("ć")
:x:É::Send("É")
:x:é::Send("é")
:x:Ǵ::Send("Ǵ")
:x:ǵ::Send("ǵ")
:x:Ḱ::Send("Ḱ")
:x:ḱ::Send("ḱ")
:x:Í::Send("Í")
:x:í::Send("í")
:x:Ĺ::Send("Ĺ")
:x:ĺ::Send("ĺ")
:x:Ḿ::Send("Ḿ")
:x:ḿ::Send("ḿ")
:x:Ń::Send("Ń")
:x:ń::Send("ń")
:x:Ó::Send("Ó")
:x:ó::Send("ó")
:x:Ṕ::Send("Ṕ")
:x:ṕ::Send("ṕ")
:x:Ŕ::Send("Ŕ")
:x:ŕ::Send("ŕ")
:x:Ś::Send("Ś")
:x:ś::Send("ś")
:x:Ú::Send("Ú")
:x:ú::Send("ú")
:x:Ẃ::Send("Ẃ")
:x:ẃ::Send("ẃ")
:x:Ý::Send("Ý")
:x:ý::Send("ý")
:x:Ź::Send("Ź")
:x:ź::Send("ź")

; Double Acute
:x:Ő::Send("Ő")
:x:ő::Send("ő")
:x:Ű::Send("Ű")
:x:ű::Send("ű")

; Grave
:x:À::Send("À")
:x:à::Send("à")
:x:È::Send("È")
:x:è::Send("è")
:x:Ì::Send("Ì")
:x:ì::Send("ì")
:x:Ǹ::Send("Ǹ")
:x:ǹ::Send("ǹ")
:x:Ò::Send("Ò")
:x:ò::Send("ò")
:x:Ù::Send("Ù")
:x:ù::Send("ù")
:x:Ẁ::Send("Ẁ")
:x:ẁ::Send("ẁ")
:x:Ỳ::Send("Ỳ")
:x:ỳ::Send("ỳ")

; Double Grave
:x:Ȁ::Send("Ȁ")
:x:ȁ::Send("ȁ")
:x:Ȅ::Send("Ȅ")
:x:ȅ::Send("ȅ")
:x:Ȉ::Send("Ȉ")
:x:ȉ::Send("ȉ")
:x:Ȍ::Send("Ȍ")
:x:ȍ::Send("ȍ")
:x:Ȑ::Send("Ȑ")
:x:ȑ::Send("ȑ")
:x:Ȕ::Send("Ȕ")
:x:ȕ::Send("ȕ")

; Circumflex
:x:Â::Send("Â")
:x:â::Send("â")
:x:Ĉ::Send("Ĉ")
:x:ĉ::Send("ĉ")
:x:Ê::Send("Ê")
:x:ê::Send("ê")
:x:Ĝ::Send("Ĝ")
:x:ĝ::Send("ĝ")
:x:Ĥ::Send("Ĥ")
:x:ĥ::Send("ĥ")
:x:Î::Send("Î")
:x:î::Send("î")
:x:Ĵ::Send("Ĵ")
:x:ĵ::Send("ĵ")
:x:Ô::Send("Ô")
:x:ô::Send("ô")
:x:Ŝ::Send("Ŝ")
:x:ŝ::Send("ŝ")
:x:Û::Send("Û")
:x:û::Send("û")
:x:Ŵ::Send("Ŵ")
:x:ŵ::Send("ŵ")
:x:Ŷ::Send("Ŷ")
:x:ŷ::Send("ŷ")
:x:Ẑ::Send("Ẑ")
:x:ẑ::Send("ẑ")

; Caron
:x:Ǎ::Send("Ǎ")
:x:ǎ::Send("ǎ")
:x:Č::Send("Č")
:x:č::Send("č")
:x:Ď::Send("Ď")
:x:ď::Send("ď")
:x:Ě::Send("Ě")
:x:ě::Send("ě")
:x:Ǧ::Send("Ǧ")
:x:ǧ::Send("ǧ")
:x:Ȟ::Send("Ȟ")
:x:ȟ::Send("ȟ")
:x:Ǩ::Send("Ǩ")
:x:ǩ::Send("ǩ")
:x:Ǐ::Send("Ǐ")
:x:ǐ::Send("ǐ")
:x:ǰ::Send("ǰ")
:x:Ľ::Send("Ľ")
:x:ľ::Send("ľ")
:x:Ň::Send("Ň")
:x:ň::Send("ň")
:x:Ǒ::Send("Ǒ")
:x:ǒ::Send("ǒ")
:x:Ř::Send("Ř")
:x:ř::Send("ř")
:x:Š::Send("Š")
:x:š::Send("š")
:x:Ť::Send("Ť")
:x:ť::Send("ť")
:x:Ǔ::Send("Ǔ")
:x:ǔ::Send("ǔ")
:x:Ž::Send("Ž")
:x:ž::Send("ž")
:x:Ǯ::Send("Ǯ")
:x:ǯ::Send("ǯ")

; Caron Below
:x:Ḓ::Send("Ḓ")
:x:ḓ::Send("ḓ")
:x:Ḙ::Send("Ḙ")
:x:ḙ::Send("ḙ")
:x:Ḽ::Send("Ḽ")
:x:ḽ::Send("ḽ")
:x:Ṋ::Send("Ṋ")
:x:ṋ::Send("ṋ")
:x:Ṱ::Send("Ṱ")
:x:ṱ::Send("ṱ")
:x:Ṷ::Send("Ṷ")
:x:ṷ::Send("ṷ")

; Macron
:x:Ā::Send("Ā")
:x:ā::Send("ā")
:x:Ē::Send("Ē")
:x:ē::Send("ē")
:x:Ḡ::Send("Ḡ")
:x:ḡ::Send("ḡ")
:x:Ī::Send("Ī")
:x:ī::Send("ī")
:x:Ō::Send("Ō")
:x:ō::Send("ō")
:x:Ū::Send("Ū")
:x:ū::Send("ū")
:x:Ȳ::Send("Ȳ")
:x:ȳ::Send("ȳ")

; Macron Below
:x:Ḇ::Send("Ḇ")
:x:ḇ::Send("ḇ")
:x:Ḏ::Send("Ḏ")
:x:ḏ::Send("ḏ")
:x:ẖ::Send("ẖ")
:x:Ḵ::Send("Ḵ")
:x:ḵ::Send("ḵ")
:x:Ḻ::Send("Ḻ")
:x:ḻ::Send("ḻ")
:x:Ṉ::Send("Ṉ")
:x:ṉ::Send("ṉ")
:x:Ṟ::Send("Ṟ")
:x:ṟ::Send("ṟ")
:x:Ṯ::Send("Ṯ")
:x:ṯ::Send("ṯ")
:x:Ẕ::Send("Ẕ")
:x:ẕ::Send("ẕ")

; Breve
:x:Ă::Send("Ă")
:x:ă::Send("ă")
:x:Ĕ::Send("Ĕ")
:x:ĕ::Send("ĕ")
:x:Ğ::Send("Ğ")
:x:ğ::Send("ğ")
:x:Ĭ::Send("Ĭ")
:x:ĭ::Send("ĭ")
:x:Ŏ::Send("Ŏ")
:x:ŏ::Send("ŏ")
:x:Ŭ::Send("Ŭ")
:x:ŭ::Send("ŭ")

; Breve Below
:x:Ḫ::Send("Ḫ")
:x:ḫ::Send("ḫ")

; Inverted Breve
:x:Ȃ::Send("Ȃ")
:x:ȃ::Send("ȃ")
:x:Ȇ::Send("Ȇ")
:x:ȇ::Send("ȇ")
:x:Ȋ::Send("Ȋ")
:x:ȋ::Send("ȋ")
:x:Ȏ::Send("Ȏ")
:x:ȏ::Send("ȏ")
:x:Ȓ::Send("Ȓ")
:x:ȓ::Send("ȓ")
:x:Ȗ::Send("Ȗ")
:x:ȗ::Send("ȗ")

; Diaeresis / Umlaut
:x:Ä::Send("Ä")
:x:ä::Send("ä")
:x:Ë::Send("Ë")
:x:ë::Send("ë")
:x:Ḧ::Send("Ḧ")
:x:ḧ::Send("ḧ")
:x:Ï::Send("Ï")
:x:ï::Send("ï")
:x:Ö::Send("Ö")
:x:ö::Send("ö")
:x:ẗ::Send("ẗ")
:x:Ü::Send("Ü")
:x:ü::Send("ü")
:x:Ẅ::Send("Ẅ")
:x:ẅ::Send("ẅ")
:x:Ẍ::Send("Ẍ")
:x:ẍ::Send("ẍ")
:x:Ÿ::Send("Ÿ")
:x:ÿ::Send("ÿ")

; Diaeresis / Umlaut Below
:x:Ṳ::Send("Ṳ")
:x:ṳ::Send("ṳ")

; Dot Above
:x:Ȧ::Send("Ȧ")
:x:ȧ::Send("ȧ")
:x:Ḃ::Send("Ḃ")
:x:ḃ::Send("ḃ")
:x:Ċ::Send("Ċ")
:x:ċ::Send("ċ")
:x:Ḋ::Send("Ḋ")
:x:ḋ::Send("ḋ")
:x:Ė::Send("Ė")
:x:ė::Send("ė")
:x:Ḟ::Send("Ḟ")
:x:ḟ::Send("ḟ")
:x:Ġ::Send("Ġ")
:x:ġ::Send("ġ")
:x:Ḣ::Send("Ḣ")
:x:ḣ::Send("ḣ")
:x:İ::Send("İ")
:x:Ṁ::Send("Ṁ")
:x:ṁ::Send("ṁ")
:x:Ṅ::Send("Ṅ")
:x:ṅ::Send("ṅ")
:x:Ȯ::Send("Ȯ")
:x:ȯ::Send("ȯ")
:x:Ṗ::Send("Ṗ")
:x:ṗ::Send("ṗ")
:x:Ṙ::Send("Ṙ")
:x:ṙ::Send("ṙ")
:x:Ṡ::Send("Ṡ")
:x:ṡ::Send("ṡ")
:x:ẛ::Send("ẛ")
:x:Ṫ::Send("Ṫ")
:x:ṫ::Send("ṫ")
:x:Ẇ::Send("Ẇ")
:x:ẇ::Send("ẇ")
:x:Ẋ::Send("Ẋ")
:x:ẋ::Send("ẋ")
:x:Ẏ::Send("Ẏ")
:x:ẏ::Send("ẏ")
:x:Ż::Send("Ż")
:x:ż::Send("ż")

; Dot Below
:x:Ạ::Send("Ạ")
:x:ạ::Send("ạ")
:x:Ḅ::Send("Ḅ")
:x:ḅ::Send("ḅ")
:x:Ḍ::Send("Ḍ")
:x:ḍ::Send("ḍ")
:x:Ẹ::Send("Ẹ")
:x:ẹ::Send("ẹ")
:x:Ḥ::Send("Ḥ")
:x:ḥ::Send("ḥ")
:x:Ị::Send("Ị")
:x:ị::Send("ị")
:x:Ḳ::Send("Ḳ")
:x:ḳ::Send("ḳ")
:x:Ḷ::Send("Ḷ")
:x:ḷ::Send("ḷ")
:x:Ṃ::Send("Ṃ")
:x:ṃ::Send("ṃ")
:x:Ọ::Send("Ọ")
:x:ọ::Send("ọ")
:x:Ṛ::Send("Ṛ")
:x:ṛ::Send("ṛ")
:x:Ṣ::Send("Ṣ")
:x:ṣ::Send("ṣ")
:x:Ṭ::Send("Ṭ")
:x:ṭ::Send("ṭ")
:x:Ụ::Send("Ụ")
:x:ụ::Send("ụ")
:x:Ṿ::Send("Ṿ")
:x:ṿ::Send("ṿ")
:x:Ẉ::Send("Ẉ")
:x:ẉ::Send("ẉ")
:x:Ỵ::Send("Ỵ")
:x:ỵ::Send("ỵ")
:x:Ẓ::Send("Ẓ")
:x:ẓ::Send("ẓ")

; Ring
:x:Å::Send("Å")
:x:å::Send("å")
:x:Ů::Send("Ů")
:x:ů::Send("ů")
:x:ẘ::Send("ẘ")
:x:ẙ::Send("ẙ")

; Ring Below
:x:Ḁ::Send("Ḁ")
:x:ḁ::Send("ḁ")

; Tilde
:x:Ã::Send("Ã")
:x:ã::Send("ã")
:x:Ẽ::Send("Ẽ")
:x:ẽ::Send("ẽ")
:x:Ĩ::Send("Ĩ")
:x:ĩ::Send("ĩ")
:x:Ñ::Send("Ñ")
:x:ñ::Send("ñ")
:x:Õ::Send("Õ")
:x:õ::Send("õ")
:x:Ũ::Send("Ũ")
:x:ũ::Send("ũ")
:x:Ṽ::Send("Ṽ")
:x:ṽ::Send("ṽ")
:x:Ỹ::Send("Ỹ")
:x:ỹ::Send("ỹ")

; Tilde Below
:x:Ḛ::Send("Ḛ")
:x:ḛ::Send("ḛ")
:x:Ḭ::Send("Ḭ")
:x:ḭ::Send("ḭ")
:x:Ṵ::Send("Ṵ")
:x:ṵ::Send("ṵ")

; Ogonek
:x:Ą::Send("Ą")
:x:ą::Send("ą")
:x:Ę::Send("Ę")
:x:ę::Send("ę")
:x:Į::Send("Į")
:x:į::Send("į")
:x:Ǫ::Send("Ǫ")
:x:ǫ::Send("ǫ")
:x:Ų::Send("Ų")
:x:ų::Send("ų")

; Horn
:x:Ơ::Send("Ơ")
:x:ơ::Send("ơ")
:x:Ư::Send("Ư")
:x:ư::Send("ư")

; Cedilla
:x:Ç::Send("Ç")
:x:ç::Send("ç")
:x:Ḑ::Send("Ḑ")
:x:ḑ::Send("ḑ")
:x:Ȩ::Send("Ȩ")
:x:ȩ::Send("ȩ")
:x:Ģ::Send("Ģ")
:x:ģ::Send("ģ")
:x:Ḩ::Send("Ḩ")
:x:ḩ::Send("ḩ")
:x:Ķ::Send("Ķ")
:x:ķ::Send("ķ")
:x:Ļ::Send("Ļ")
:x:ļ::Send("ļ")
:x:Ņ::Send("Ņ")
:x:ņ::Send("ņ")
:x:Ŗ::Send("Ŗ")
:x:ŗ::Send("ŗ")
:x:Ş::Send("Ş")
:x:ş::Send("ş")
:x:Ţ::Send("Ţ")
:x:ţ::Send("ţ")

; Hook Above
:x:Ả::Send("Ả")
:x:ả::Send("ả")
:x:Ẻ::Send("Ẻ")
:x:ẻ::Send("ẻ")
:x:Ỉ::Send("Ỉ")
:x:ỉ::Send("ỉ")
:x:Ỏ::Send("Ỏ")
:x:ỏ::Send("ỏ")
:x:Ủ::Send("Ủ")
:x:ủ::Send("ủ")
:x:Ỷ::Send("Ỷ")
:x:ỷ::Send("ỷ")

; Comma
:x:D̦::Send("D̦")
:x:d̦::Send("d̦")
:x:Ș::Send("Ș")
:x:ș::Send("ș")
:x:Ț::Send("Ț")
:x:ț::Send("ț")

; Palatal Hook
:x:b̡::Send("ᶀ")
:x:C̡::Send("Ꞔ")
:x:c̡::Send("ꞔ")
:x:d̡::Send("ᶁ")
:x:ʤ̡::Send("𝼒")
:x:f̡::Send("ᶂ")
:x:g̡::Send("ᶃ")
:x:h̡::Send("ꞕ")
:x:k̡::Send("ᶄ")
:x:l̡::Send("ᶅ")
:x:ɬ̡::Send("𝼓")
:x:m̡::Send("ᶆ")
:x:n̡::Send("ᶇ")
:x:ŋ̡::Send("𝼔")
:x:p̡::Send("ᶈ")
:x:r̡::Send("ᶉ")
:x:ɹ̡::Send("𝼕")
:x:ɾ̡::Send("𝼖")
:x:s̡::Send("ᶊ")
:x:ʃ̡::Send("ᶋ")
:x:t̡::Send("ƫ")
:x:ʧ̡::Send("𝼗")
:x:v̡::Send("ᶌ")
:x:x̡::Send("ᶍ")
:x:Z̡::Send("Ᶎ")
:x:z̡::Send("ᶎ")
:x:ʒ̡::Send("𝼘")

; Retroflex Hook
:x:a̢::Send("ᶏ")
:x:c̢::Send("𝼝")
:x:ɔ̢::Send("ᶗ")
:x:D̢::Send("Ɖ")
:x:d̢::Send("ɖ")
:x:ɗ̢::Send("ᶑ")
:x:ʤ̢::Send("𝼙")
:x:e̢::Send("ᶒ")
:x:ə̢::Send("ᶕ")
:x:i̢::Send("ᶖ")
:x:ɨ̢::Send("𝼚")
:x:l̢::Send("ɭ")
:x:ɬ̢::Send("ꞎ")
:x:ɮ̢::Send("𝼅")
:x:n̢::Send("ɳ")
:x:o̢::Send("𝼛")
:x:R̢::Send("Ɽ")
:x:r̢::Send("ɽ")
:x:ɹ̢::Send("ɻ")
:x:S̢::Send("Ʂ")
:x:s̢::Send("ʂ")
:x:ʃ̢::Send("ᶘ")
:x:T̢::Send("Ʈ")
:x:t̢::Send("ʈ")
:x:ƭ̢::Send("𝼉")
:x:ʧ̢::Send("𝼜")
:x:u̢::Send("ᶙ")
:x:z̢::Send("ʐ")
:x:ʒ̢::Send("ᶚ")
:x:ɑ̢::Send("ᶐ")
:x:ɛ̢::Send("ᶓ")
:x:ɜ̢::Send("ᶔ")
:x:ǃ̢::Send("𝼊")

; Stroke
:x:Ꜹ̵::Send("Ꜻ")
:x:ꜹ̵::Send("ꜻ")
:x:B̵::Send("Ƀ")
:x:b̵::Send("ƀ")
:x:C̵::Send("Ꞓ")
:x:c̵::Send("ꞓ")
:x:D̵::Send("Đ")
:x:d̵::Send("đ")
:x:e̵::Send("ꬳ")
:x:F̵::Send("Ꞙ")
:x:f̵::Send("ꞙ")
:x:G̵::Send("Ǥ")
:x:g̵::Send("ǥ")
:x:H̵::Send("Ħ")
:x:h̵::Send("ħ")
:x:I̵::Send("Ɨ")
:x:i̵::Send("ɨ")
:x:J̵::Send("Ɉ")
:x:j̵::Send("ɉ")
:x:ȷ̵::Send("ɟ")
:x:K̵::Send("Ꝁ")
:x:k̵::Send("ꝁ")
:x:Ꝃ̵::Send("Ꝅ")
:x:ꝃ̵::Send("ꝅ")
:x:L̵::Send("Ƚ")
:x:l̵::Send("ƚ")
:x:O̵::Send("Ɵ")
:x:o̵::Send("ɵ")
:x:P̵::Send("Ᵽ")
:x:p̵::Send("ᵽ")
:x:R̵::Send("Ɍ")
:x:r̵::Send("ɍ")
:x:S̵::Send("Ꟊ")
:x:s̵::Send("ꟊ")
:x:T̵::Send("Ŧ")
:x:t̵::Send("ŧ")
:x:Þ̵::Send("Ꝥ")
:x:þ̵::Send("ꝥ")
:x:U̵::Send("Ʉ")
:x:u̵::Send("ʉ")
:x:Y̵::Send("Ɏ")
:x:y̵::Send("ɏ")
:x:Z̵::Send("Ƶ")
:x:z̵::Send("ƶ")
:x:2̵::Send("ƻ")
:x:ɑ̵::Send("ꬰ")
:x:ɩ̵::Send("ᵼ")
:x:Ꟛ̵::Send("Ƛ")
:x:ꟛ̵::Send("ƛ")
:x:ſ̵::Send("ẝ")
:x:ʊ̵::Send("ᵿ")
:x:ʔ̵::Send("ʡ")
:x:ʕ̵::Send("ʢ")
:x:ʖ̵::Send("ƾ")

; Long Stroke
:x:O̶::Send("Ꝋ")
:x:o̶::Send("ꝋ")

; Solidus
:x:G̷::Send("Ꞡ")
:x:g̷::Send("ꞡ")
:x:K̷::Send("Ꞣ")
:x:k̷::Send("ꞣ")
:x:L̷::Send("Ł")
:x:l̷::Send("ł")
:x:N̷::Send("Ꞥ")
:x:n̷::Send("ꞥ")
:x:O̷::Send("Ø")
:x:o̷::Send("ø")
:x:R̷::Send("Ꞧ")
:x:r̷::Send("ꞧ")
:x:S̷::Send("Ꞩ")
:x:s̷::Send("ꞩ")
:x:ſ̷::Send("ẜ")

; Long Solidus
:x:A̸::Send("Ⱥ")
:x:a̸::Send("ⱥ")
:x:C̸::Send("Ȼ")
:x:c̸::Send("ȼ")
:x:ɔ̸::Send("ꬿ")
:x:E̸::Send("Ɇ")
:x:e̸::Send("ɇ")
:x:K̸::Send("Ꝃ")
:x:k̸::Send("ꝃ")
:x:Ꝁ̸::Send("Ꝅ")
:x:ꝁ̸::Send("ꝅ")
:x:L̸::Send("Ł")
:x:l̸::Send("ł")
:x:O̸::Send("Ø")
:x:o̸::Send("ø")
:x:Q̸::Send("Ꝙ")
:x:q̸::Send("ꝙ")
:x:S̸::Send("Ꟍ")
:x:s̸::Send("ꟍ")
:x:T̸::Send("Ⱦ")
:x:t̸::Send("ⱦ")
:x:U̸::Send("Ꞹ")
:x:u̸::Send("ꞹ")
:x:V̸::Send("Ꝟ")
:x:v̸::Send("ꝟ")

; Nordic Compounds
:x:Ǻ::Send("Ǻ")
:x:ǻ::Send("ǻ")
:x:Ǽ::Send("Ǽ")
:x:ǽ::Send("ǽ")
:x:Ǣ::Send("Ǣ")
:x:ǣ::Send("ǣ")
:x:Ǿ::Send("Ǿ")
:x:ǿ::Send("ǿ")

; Miscellaneous Compounds in Latin Extended-B
:x:Ǟ::Send("Ǟ")
:x:ǟ::Send("ǟ")
:x:Ǡ::Send("Ǡ")
:x:ǡ::Send("ǡ")
:x:Ȫ::Send("Ȫ")
:x:ȫ::Send("ȫ")
:x:Ȭ::Send("Ȭ")
:x:ȭ::Send("ȭ")
:x:Ȱ::Send("Ȱ")
:x:ȱ::Send("ȱ")
:x:Ǖ::Send("Ǖ")
:x:ǖ::Send("ǖ")
:x:Ǘ::Send("Ǘ")
:x:ǘ::Send("ǘ")
:x:Ǚ::Send("Ǚ")
:x:ǚ::Send("ǚ")
:x:Ǜ::Send("Ǜ")
:x:ǜ::Send("ǜ")

; Miscellaneous Compounds in Latin Extended Additional
:x:Ḉ::Send("Ḉ")
:x:ḉ::Send("ḉ")
:x:Ḉ::Send("Ḉ")
:x:ḉ::Send("ḉ")
:x:Ḕ::Send("Ḕ")
:x:ḕ::Send("ḕ")
:x:Ḗ::Send("Ḗ")
:x:ḗ::Send("ḗ")
:x:Ḝ::Send("Ḝ")
:x:ḝ::Send("ḝ")
:x:Ḝ::Send("Ḝ")
:x:ḝ::Send("ḝ")
:x:Ḯ::Send("Ḯ")
:x:ḯ::Send("ḯ")
:x:Ḹ::Send("Ḹ")
:x:ḹ::Send("ḹ")
:x:Ḹ::Send("Ḹ")
:x:ḹ::Send("ḹ")
:x:Ǭ::Send("Ǭ")
:x:ǭ::Send("ǭ")
:x:Ǭ::Send("Ǭ")
:x:ǭ::Send("ǭ")
:x:Ṑ::Send("Ṑ")
:x:ṑ::Send("ṑ")
:x:Ṓ::Send("Ṓ")
:x:ṓ::Send("ṓ")
:x:Ṍ::Send("Ṍ")
:x:ṍ::Send("ṍ")
:x:Ṏ::Send("Ṏ")
:x:ṏ::Send("ṏ")
:x:Ṝ::Send("Ṝ")
:x:ṝ::Send("ṝ")
:x:Ṝ::Send("Ṝ")
:x:ṝ::Send("ṝ")
:x:Ṥ::Send("Ṥ")
:x:ṥ::Send("ṥ")
:x:Ṧ::Send("Ṧ")
:x:ṧ::Send("ṧ")
:x:Ṩ::Send("Ṩ")
:x:ṩ::Send("ṩ")
:x:Ṩ::Send("Ṩ")
:x:ṩ::Send("ṩ")
:x:Ṹ::Send("Ṹ")
:x:ṹ::Send("ṹ")
:x:Ṻ::Send("Ṻ")
:x:ṻ::Send("ṻ")

; Vietnamese Compounds
:x:Ằ::Send("Ằ")
:x:ằ::Send("ằ")
:x:Ẳ::Send("Ẳ")
:x:ẳ::Send("ẳ")
:x:Ẵ::Send("Ẵ")
:x:ẵ::Send("ẵ")
:x:Ắ::Send("Ắ")
:x:ắ::Send("ắ")
:x:Ặ::Send("Ặ")
:x:ặ::Send("ặ")
:x:Ặ::Send("Ặ")
:x:ặ::Send("ặ")
:x:Ầ::Send("Ầ")
:x:ầ::Send("ầ")
:x:Ẩ::Send("Ẩ")
:x:ẩ::Send("ẩ")
:x:Ẫ::Send("Ẫ")
:x:ẫ::Send("ẫ")
:x:Ấ::Send("Ấ")
:x:ấ::Send("ấ")
:x:Ậ::Send("Ậ")
:x:ậ::Send("ậ")
:x:Ậ::Send("Ậ")
:x:ậ::Send("ậ")
:x:Ề::Send("Ề")
:x:ề::Send("ề")
:x:Ể::Send("Ể")
:x:ể::Send("ể")
:x:Ễ::Send("Ễ")
:x:ễ::Send("ễ")
:x:Ế::Send("Ế")
:x:ế::Send("ế")
:x:Ệ::Send("Ệ")
:x:ệ::Send("ệ")
:x:Ệ::Send("Ệ")
:x:ệ::Send("ệ")
:x:Ồ::Send("Ồ")
:x:ồ::Send("ồ")
:x:Ổ::Send("Ổ")
:x:ổ::Send("ổ")
:x:Ỗ::Send("Ỗ")
:x:ỗ::Send("ỗ")
:x:Ố::Send("Ố")
:x:ố::Send("ố")
:x:Ộ::Send("Ộ")
:x:ộ::Send("ộ")
:x:Ộ::Send("Ộ")
:x:ộ::Send("ộ")
:x:Ờ::Send("Ờ")
:x:ờ::Send("ờ")
:x:Ờ::Send("Ờ")
:x:ờ::Send("ờ")
:x:Ở::Send("Ở")
:x:ở::Send("ở")
:x:Ở::Send("Ở")
:x:ở::Send("ở")
:x:Ỡ::Send("Ỡ")
:x:ỡ::Send("ỡ")
:x:Ỡ::Send("Ỡ")
:x:ỡ::Send("ỡ")
:x:Ớ::Send("Ớ")
:x:ớ::Send("ớ")
:x:Ớ::Send("Ớ")
:x:ớ::Send("ớ")
:x:Ợ::Send("Ợ")
:x:ợ::Send("ợ")
:x:Ợ::Send("Ợ")
:x:ợ::Send("ợ")
:x:Ừ::Send("Ừ")
:x:ừ::Send("ừ")
:x:Ừ::Send("Ừ")
:x:ừ::Send("ừ")
:x:Ử::Send("Ử")
:x:ử::Send("ử")
:x:Ử::Send("Ử")
:x:ử::Send("ử")
:x:Ữ::Send("Ữ")
:x:ữ::Send("ữ")
:x:Ữ::Send("Ữ")
:x:ữ::Send("ữ")
:x:Ứ::Send("Ứ")
:x:ứ::Send("ứ")
:x:Ứ::Send("Ứ")
:x:ứ::Send("ứ")
:x:Ự::Send("Ự")
:x:ự::Send("ự")
:x:Ự::Send("Ự")
:x:ự::Send("ự")

/**************
 * HOTSTRINGS *
 **************/

; Ligatures & Miscellaneous Letters
:x:⁅AA⁆::Send("Ꜳ")
:x:⁅aa⁆::Send("ꜳ")
:x:⁅AE⁆::Send("Æ")
:x:⁅ae⁆::Send("æ")
:x:⁅ain⁆::Send("ᴥ")
:x:⁅AO⁆::Send("Ꜵ")
:x:⁅ao⁆::Send("ꜵ")
:x:⁅AU⁆::Send("Ꜷ")
:x:⁅au⁆::Send("ꜷ")
:x:⁅AV⁆::Send("Ꜹ")
:x:⁅av⁆::Send("ꜹ")
:x:⁅AY⁆::Send("Ꜽ")
:x:⁅ay⁆::Send("ꜽ")
:x:⁅co⁆::Send("ꭃ")
:x:⁅cø⁆::Send("ꭄ")
:x:⁅CZ⁆::Send("Ꝣ")
:x:⁅cz⁆::Send("ꝣ")
:x:⁅db⁆::Send("ȸ")
:x:⁅DH⁆::Send("Ð")
:x:⁅dh⁆::Send("ð")
:x:⁅dz⁆::Send("ʣ")
:x:⁅dzh⁆::Send("ʤ")
:x:⁅dʐ⁆::Send("ꭦ")
:x:⁅f⁆::Send("ꬵ")
:x:⁅ff⁆::Send("ﬀ")
:x:⁅ffi⁆::Send("ﬃ")
:x:⁅ffl⁆::Send("ﬄ")
:x:⁅fi⁆::Send("ﬁ")
:x:⁅fl⁆::Send("ﬂ")
:x:⁅fng⁆::Send("ʩ")
:x:⁅ft⁆::Send("ﬅ")
:x:⁅HNG⁆::Send("Ꜧ")
:x:⁅hng⁆::Send("ꜧ")
:x:⁅HW⁆::Send("Ƕ")
:x:⁅hw⁆::Send("ƕ")
:x:⁅LL⁆::Send("Ꝇ")
:x:⁅ll⁆::Send("ꝇ")
:x:⁅ls⁆::Send("ʪ")
:x:⁅LSH⁆::Send("Ɬ")
:x:⁅lsh⁆::Send("ɬ")
:x:⁅lr⁆::Send("𝼑")
:x:⁅lz⁆::Send("ʫ")
:x:⁅lzh⁆::Send("ɮ")
:x:⁅MG⁆::Send("Ɱ")
:x:⁅mg⁆::Send("ɱ")
:x:⁅NG⁆::Send("Ŋ")
:x:⁅ng⁆::Send("ŋ")
:x:⁅NH⁆::Send("Ƞ")
:x:⁅nh⁆::Send("ƞ")
:x:⁅NJ⁆::Send("Ɲ")
:x:⁅nj⁆::Send("ɲ")
:x:⁅OE⁆::Send("Œ")
:x:⁅oe⁆::Send("œ")
:x:⁅OO⁆::Send("Ꝏ")
:x:⁅oo⁆::Send("ꝏ")
:x:⁅OU⁆::Send("Ȣ")
:x:⁅ou⁆::Send("ȣ")
:x:⁅ph⁆::Send("ɸ")
:x:⁅qp⁆::Send("ȹ")
:x:⁅rr⁆::Send("ꭈ")
:x:⁅SH⁆::Send("Ʃ")
:x:⁅sh⁆::Send("ʃ")
:x:⁅sh&⁆::Send("ꭍ")
:x:⁅shw⁆::Send("ƪ")
:x:⁅st⁆::Send("ﬆ")
:x:⁅SW⁆::Send("Ȿ")
:x:⁅sw⁆::Send("ȿ")
:x:⁅SZ⁆::Send("ẞ")
:x:⁅sz⁆::Send("ß")
:x:⁅TH⁆::Send("Þ")
:x:⁅th⁆::Send("þ")
:x:⁅thth⁆::Send("ꟓ")
:x:⁅ts⁆::Send("ʦ")
:x:⁅tsh⁆::Send("ʧ")
:x:⁅tʂ⁆::Send("ꭧ")
:x:⁅TZ⁆::Send("Ꜩ")
:x:⁅tz⁆::Send("ꜩ")
:x:⁅ue⁆::Send("ᵫ")
:x:⁅ui⁆::Send("ꭐ")
:x:⁅uo⁆::Send("ꭣ")
:x:⁅VY⁆::Send("Ꝡ")
:x:⁅VY⁆::Send("ꝡ")
:x:⁅ww⁆::Send("ʬ")
:x:⁅ZH⁆::Send("Ʒ")
:x:⁅zh⁆::Send("ʒ")
:x:⁅zhw⁆::Send("ƺ")
:x:⁅ZW⁆::Send("Ɀ")
:x:⁅zw⁆::Send("ɀ")
:x:⁅'n⁆::Send("ŉ")
:x:⁅/W⁆::Send("ꟿ")

; Scribal Abbreviations
:x:⁅CUM⁆::Send("Ꝯ")
:x:⁅cum⁆::Send("ꝯ")
:x:⁅dum⁆::Send("ꝱ")
:x:⁅ET⁆::Send("Ꝫ")
:x:⁅et⁆::Send("ꝫ")
:x:⁅IS⁆::Send("Ꝭ")
:x:⁅is⁆::Send("ꝭ")
:x:⁅lum⁆::Send("ꝲ")
:x:⁅mum⁆::Send("ꝳ")
:x:⁅num⁆::Send("ꝴ")
:x:⁅rum⁆::Send("ꝵ")
:x:⁅-RUM⁆::Send("ꝶ")
:x:⁅tum⁆::Send("ꝷ")
:x:⁅um⁆::Send("ꝸ")
:x:⁅US⁆::Send("Ꝯ")
:x:⁅us⁆::Send("ꝯ")

; Lookalikes
:x:⁅Å&⁆::Send("Å")
:x:⁅K&⁆::Send("K")
:x:⁅Đ&⁆::Send("Ꟈ")
:x:⁅đ&⁆::Send("ꟈ")

; Middle Dot
:x:⁅L·⁆::Send("Ŀ")
:x:⁅l·⁆::Send("ŀ")
:x:⁅O·⁆::Send("ʘ")

; Middle Ring
:x:⁅l@⁆::Send("ꬹ")
:x:⁅O@⁆::Send("Ꝍ")
:x:⁅o@⁆::Send("ꝍ")
:x:⁅x@⁆::Send("ꭖ")

; Middle Tilde
:x:⁅b~⁆::Send("ᵬ")
:x:⁅d~⁆::Send("ᵭ")
:x:⁅f~⁆::Send("ᵮ")
:x:⁅m~⁆::Send("ᵯ")
:x:⁅n~⁆::Send("ᵰ")
:x:⁅L~⁆::Send("Ɫ")
:x:⁅l~⁆::Send("ɫ")
:x:⁅l~&⁆::Send("ꬷ")
:x:⁅l~~⁆::Send("ꬸ")
:x:⁅p~⁆::Send("ᵱ")
:x:⁅r~⁆::Send("ᵲ")
:x:⁅s~⁆::Send("ᵴ")
:x:⁅t~⁆::Send("ᵵ")
:x:⁅z~⁆::Send("ᵶ")

; High Stroke
:x:⁅L-⁆::Send("Ꝉ")
:x:⁅l-⁆::Send("ꝉ")

; Double Bar
:x:⁅L=⁆::Send("Ⱡ")
:x:⁅l=⁆::Send("ⱡ")
:x:⁅sh=⁆::Send("𝼋")

; Through Descender
:x:⁅P_⁆::Send("Ꝑ")
:x:⁅p_⁆::Send("ꝑ")
:x:⁅Q_⁆::Send("Ꝗ")
:x:⁅q_⁆::Send("ꝗ")
:x:⁅TH_⁆::Send("Ꝧ")
:x:⁅th_⁆::Send("ꝧ")

; Hook
:x:⁅B'⁆::Send("Ɓ")
:x:⁅b'⁆::Send("ɓ")
:x:⁅C'⁆::Send("Ƈ")
:x:⁅c'⁆::Send("ƈ")
:x:⁅D'⁆::Send("Ɗ")
:x:⁅d'⁆::Send("ɗ")
:x:⁅ɖ'⁆::Send("ᶑ")
:x:⁅F'⁆::Send("Ƒ")
:x:⁅f'⁆::Send("ƒ")
:x:⁅fng'⁆::Send("𝼀")
:x:⁅G'⁆::Send("Ɠ")
:x:⁅g'⁆::Send("ɠ")
:x:⁅H'⁆::Send("Ɦ")
:x:⁅h'⁆::Send("ɦ")
:x:⁅hng'⁆::Send("ɧ")
:x:⁅K'⁆::Send("Ƙ")
:x:⁅k'⁆::Send("ƙ")
:x:⁅M'⁆::Send("Ɱ")
:x:⁅m'⁆::Send("ɱ")
:x:⁅N'⁆::Send("Ɲ")
:x:⁅n'⁆::Send("ɲ")
:x:⁅P'⁆::Send("Ƥ")
:x:⁅p'⁆::Send("ƥ")
:x:⁅Q'⁆::Send("Ɋ")
:x:⁅q'⁆::Send("ɋ")
:x:⁅q'&⁆::Send("ʠ")
:x:⁅R'⁆::Send("Ɽ")
:x:⁅r'⁆::Send("ɽ")
:x:⁅T'⁆::Send("Ƭ")
:x:⁅t'⁆::Send("ƭ")
:x:⁅u'⁆::Send("ꭒ")
:x:⁅v'⁆::Send("ⱱ")
:x:⁅W'⁆::Send("Ⱳ")
:x:⁅w'⁆::Send("ⱳ")
:x:⁅Y'⁆::Send("Ƴ")
:x:⁅y'⁆::Send("ƴ")
:x:⁅Z'⁆::Send("Ȥ")
:x:⁅z'⁆::Send("ȥ")

; Curl
:x:⁅c,⁆::Send("ɕ")
:x:⁅c,&⁆::Send("𝼞")
:x:⁅d,⁆::Send("ȡ")
:x:⁅dz,⁆::Send("ʥ")
:x:⁅l,⁆::Send("ȴ")
:x:⁅ls,⁆::Send("𝼆")
:x:⁅n,⁆::Send("ȵ")
:x:⁅s,⁆::Send("ɕ")
:x:⁅s,&⁆::Send("𝼞")
:x:⁅sh,⁆::Send("ʆ")
:x:⁅sh,=⁆::Send("𝼌")
:x:⁅t,⁆::Send("ȶ")
:x:⁅ts,⁆::Send("ʨ")
:x:⁅v,⁆::Send("ⱴ")
:x:⁅zh,⁆::Send("ʓ")
:x:⁅z,⁆::Send("ʑ")

; Crossed Tail
:x:⁅ng;⁆::Send("ꬼ")
:x:⁅g;⁆::Send("ꬶ")
:x:⁅J;⁆::Send("Ʝ")
:x:⁅j;⁆::Send("ʝ")
:x:⁅m;⁆::Send("ꬺ")
:x:⁅n;⁆::Send("ꬻ")
:x:⁅r;⁆::Send("ꭉ")
:x:⁅rr;⁆::Send("ꭊ")

; Descender
:x:⁅H.⁆::Send("Ⱨ")
:x:⁅h.⁆::Send("ⱨ")
:x:⁅K.⁆::Send("Ⱪ")
:x:⁅k.⁆::Send("ⱪ")
:x:⁅N.⁆::Send("Ꞑ")
:x:⁅n.⁆::Send("ꞑ")
:x:⁅Z.⁆::Send("Ⱬ")
:x:⁅z.⁆::Send("ⱬ")

; Flourish
:x:⁅,B⁆::Send("Ꞗ")
:x:⁅,b⁆::Send("ꞗ")
:x:⁅,e⁆::Send("ꬴ")
:x:⁅,P⁆::Send("Ꝓ")
:x:⁅,p⁆::Send("ꝓ")
:x:⁅,P&⁆::Send("Ꝕ")
:x:⁅,p&⁆::Send("ꝕ")

; Mid-Height Left Hook
:x:⁅ɖ&⁆::Send("𝼥")
:x:⁅ɭ&⁆::Send("𝼦")
:x:⁅ɳ&⁆::Send("𝼧")
:x:⁅ɽ&⁆::Send("𝼨")
:x:⁅ʂ&⁆::Send("𝼩")
:x:⁅ʈ&⁆::Send("𝼪")

; Rotated, Reversed, and Extended Letters
:x:⁅A?⁆::Send("Ɐ")
:x:⁅a?⁆::Send("ɐ")
:x:⁅ae?⁆::Send("ᴂ")
:x:⁅a e?!⁆::Send("ꬱ")
:x:⁅C?⁆::Send("Ɔ")
:x:⁅c?⁆::Send("ɔ")
:x:⁅c?<⁆::Send("ᴒ")
:x:⁅c?e⁆::Send("ꭢ")
:x:⁅C!⁆::Send("Ↄ")
:x:⁅c!⁆::Send("ↄ")
:x:⁅C!·⁆::Send("Ꜿ")
:x:⁅c!·⁆::Send("ꜿ")
:x:⁅c|⁆::Send("ʗ")
:x:⁅c|,⁆::Send("𝼏")
:x:⁅c>⁆::Send("ᴒ")
:x:⁅E?⁆::Send("Ǝ")
:x:⁅+e?⁆::Send("Ə")
:x:⁅e?⁆::Send("ə")
:x:⁅e?&⁆::Send("ǝ")
:x:⁅e?'⁆::Send("ɚ")
:x:⁅E!⁆::Send("Ǝ")
:x:⁅e!⁆::Send("ɘ")
:x:⁅F?⁆::Send("Ⅎ")
:x:⁅f?⁆::Send("ɟ")
:x:⁅f?'⁆::Send("ʄ")
:x:⁅F!⁆::Send("ꟻ")
:x:⁅+g⁆::Send("Ɡ")
:x:⁅G?⁆::Send("⅁")
:x:⁅g?⁆::Send("ᵷ")
:x:⁅g!⁆::Send("𝼁")
:x:⁅+h?⁆::Send("Ɥ")
:x:⁅h?⁆::Send("ɥ")
:x:⁅h?'⁆::Send("ʮ")
:x:⁅h?''⁆::Send("ʯ")
:x:⁅I!⁆::Send("ꟾ")
:x:⁅I>⁆::Send("ꟷ")
:x:⁅i?⁆::Send("ᴉ")
:x:⁅K?⁆::Send("Ʞ")
:x:⁅k?⁆::Send("ʞ")
:x:⁅k!⁆::Send("𝼃")
:x:⁅L?⁆::Send("Ꞁ")
:x:⁅l?⁆::Send("ꞁ")
:x:⁅L?&⁆::Send("⅂")
:x:⁅L!⁆::Send("⅃")
:x:⁅M?⁆::Send("ꟽ")
:x:⁅+m?⁆::Send("Ɯ")
:x:⁅m?⁆::Send("ɯ")
:x:⁅m?|⁆::Send("ɰ")
:x:⁅m>⁆::Send("ᴟ")
:x:⁅m?<⁆::Send("ᴟ")
:x:⁅ng!⁆::Send("𝼇")
:x:⁅o>⁆::Send("ᴑ")
:x:⁅ø>⁆::Send("ᴓ")
:x:⁅oe?⁆::Send("ᴔ")
:x:⁅oe?!⁆::Send("ꭀ")
:x:⁅øe?⁆::Send("ꭁ")
:x:⁅ɵe?⁆::Send("ꭂ")
:x:⁅P!⁆::Send("ꟼ")
:x:⁅r|⁆::Send("ɼ")
:x:⁅r'?⁆::Send("ⱹ")
:x:⁅r?⁆::Send("ɹ")
:x:⁅r?'⁆::Send("ɻ")
:x:⁅r?|⁆::Send("ɺ")
:x:⁅r?|'⁆::Send("𝼈")
:x:⁅S!⁆::Send("Ƨ")
:x:⁅s!⁆::Send("ƨ")
:x:⁅s!·⁆::Send("ᴤ")
:x:⁅T?⁆::Send("Ʇ")
:x:⁅t?⁆::Send("ʇ")
:x:⁅t?,⁆::Send("𝼍")
:x:⁅u<⁆::Send("ᴝ")
:x:⁅ui?⁆::Send("ꭑ")
:x:⁅ü<⁆::Send("ᴞ")
:x:⁅V?⁆::Send("Ʌ")
:x:⁅v?⁆::Send("ʌ")
:x:⁅w?⁆::Send("ʍ")
:x:⁅Y?⁆::Send("⅄")
:x:⁅y?⁆::Send("ʎ")
:x:⁅ZH!⁆::Send("Ƹ")
:x:⁅zh!⁆::Send("ƹ")
:x:⁅2!⁆::Send("↊")
:x:⁅3!⁆::Send("↋")

; Unfragmented Letters
:x:⁅i#⁆::Send("ı")
:x:⁅j#⁆::Send("ȷ")
:x:⁅j#' ̵⁆::Send("ʄ")
:x:⁅r#⁆::Send("ɾ")
:x:⁅r#~⁆::Send("ᵳ")
:x:⁅r#!⁆::Send("ɿ")
:x:⁅r#!'⁆::Send("ʅ")
:x:⁅+?#⁆::Send("Ɂ")
:x:⁅?#⁆::Send("ʔ")
:x:⁅-?#⁆::Send("ɂ")
:x:⁅+?#!⁆::Send("꟎")
:x:⁅?#!⁆::Send("ʕ")
:x:⁅-?#!⁆::Send("꟏")
:x:⁅?#?!⁆::Send("ʖ")
:x:⁅?#?!,⁆::Send("𝼎")

; Glottal Letters
:x:⁅?#A⁆::Send("Ꞻ")
:x:⁅?#a⁆::Send("ꞻ")
:x:⁅?#I⁆::Send("Ꞽ")
:x:⁅?#i⁆::Send("ꞽ")
:x:⁅?#U⁆::Send("Ꞿ")
:x:⁅?#u⁆::Send("ꞿ")

; Variants
:x:⁅``A⁆::Send("Ɑ")
:x:⁅``a⁆::Send("ɑ")
:x:⁅``A?⁆::Send("Ɒ")
:x:⁅``a?⁆::Send("ɒ")
:x:⁅``a?!⁆::Send("ꭤ")
:x:⁅``B⁆::Send("Ꞵ")
:x:⁅``b⁆::Send("ꞵ")
:x:⁅``d⁆::Send("ẟ")
:x:⁅``d?⁆::Send("ƍ")
:x:⁅``dz⁆::Send("ƻ")
:x:⁅``E⁆::Send("Ɛ")
:x:⁅``e⁆::Send("ɛ")
:x:⁅``e?⁆::Send("ᴈ")
:x:⁅``E!⁆::Send("Ɜ")
:x:⁅``e!⁆::Send("ɜ")
:x:⁅``e!'⁆::Send("ɝ")
:x:⁅``eo⁆::Send("ʚ")
:x:⁅``eo!⁆::Send("ɞ")
:x:⁅``G⁆::Send("Ɣ")
:x:⁅``g⁆::Send("ɣ")
:x:⁅``H⁆::Send("Ⱶ")
:x:⁅``h⁆::Send("ⱶ")
:x:⁅``H!⁆::Send("Ꟶ")
:x:⁅``h!⁆::Send("ꟶ")
:x:⁅``I⁆::Send("Ɩ")
:x:⁅``i⁆::Send("ɩ")
:x:⁅``L⁆::Send("Ꟛ")
:x:⁅``l⁆::Send("ꟛ")
:x:⁅``m⁆::Send("µ")
:x:⁅``ow⁆::Send("ɷ")
:x:⁅``ph⁆::Send("ⱷ")
:x:⁅``Q⁆::Send("Ƣ")
:x:⁅``q⁆::Send("ƣ")
:x:⁅``R⁆::Send("Ꝛ")
:x:⁅``r⁆::Send("ꝛ")
:x:⁅``RUM⁆::Send("Ꝝ")
:x:⁅``rum⁆::Send("ꝝ")
:x:⁅``s⁆::Send("ſ")
:x:⁅``ts⁆::Send("ƾ")
:x:⁅``U⁆::Send("Ʊ")
:x:⁅``u⁆::Send("ʊ")
:x:⁅``V⁆::Send("Ʋ")
:x:⁅``v⁆::Send("ʋ")
:x:⁅``W⁆::Send("Ꞷ")
:x:⁅``w⁆::Send("ꞷ")
:x:⁅``X⁆::Send("Ꭓ")
:x:⁅``x⁆::Send("ꭓ")
:x:⁅``x@⁆::Send("ꭔ")
:x:⁅``Y⁆::Send("Ɤ")
:x:⁅``y⁆::Send("ɤ")
:x:⁅``|⁆::Send("ǀ")
:x:⁅``|=⁆::Send("ǂ")
:x:⁅``||⁆::Send("ǁ")
:x:⁅``!⁆::Send("ǃ")
:x:⁅+``'⁆::Send("Ꞌ")
:x:⁅``'⁆::Send("ꞌ")
:x:⁅``:⁆::Send("ː")
:x:⁅``;⁆::Send("ˑ")
:x:⁅``<⁆::Send("˂")
:x:⁅``>⁆::Send("˃")
:x:⁅``^⁆::Send("˄")
:x:⁅``^?⁆::Send("˅")
:x:⁅``·⁆::Send("ꞏ")

; Smalls & Capitals
:x:⁅-A⁆::Send("ᴀ")
:x:⁅-AE⁆::Send("ᴁ")
:x:⁅-B⁆::Send("ʙ")
:x:⁅-Ƀ⁆::Send("ᴃ")
:x:⁅-C⁆::Send("ᴄ")
:x:⁅-C?⁆::Send("ᴐ")
:x:⁅-D⁆::Send("ᴅ")
:x:⁅-Đ⁆::Send("ᴆ")
:x:⁅-E⁆::Send("ᴇ")
:x:⁅-E?⁆::Send("ⱻ")
:x:⁅-F⁆::Send("ꜰ")
:x:⁅-F?⁆::Send("ⅎ")
:x:⁅-G⁆::Send("ɢ")
:x:⁅-G?⁆::Send("𝼂")
:x:⁅-G'⁆::Send("ʛ")
:x:⁅-H⁆::Send("ʜ")
:x:⁅+-I⁆::Send("Ɪ")
:x:⁅-I⁆::Send("ɪ")
:x:⁅-Ɨ⁆::Send("ᵻ")
:x:⁅-J⁆::Send("ᴊ")
:x:⁅-K⁆::Send("ᴋ")
:x:⁅-K&⁆::Send("ĸ")
:x:⁅-K?⁆::Send("𝼐")
:x:⁅-L⁆::Send("ʟ")
:x:⁅-Ł⁆::Send("ᴌ")
:x:⁅-L&⁆::Send("ᴫ")
:x:⁅-LSH⁆::Send("𝼄")
:x:⁅-M⁆::Send("ᴍ")
:x:⁅-+m?⁆::Send("ꟺ")
:x:⁅-N⁆::Send("ɴ")
:x:⁅-N!⁆::Send("ᴎ")
:x:⁅-O⁆::Send("ᴏ")
:x:⁅-OE⁆::Send("ɶ")
:x:⁅-OU⁆::Send("ᴕ")
:x:⁅-P⁆::Send("ᴘ")
:x:⁅-Q⁆::Send("ꞯ")
:x:⁅+-R⁆::Send("Ʀ")
:x:⁅-R⁆::Send("ʀ")
:x:⁅-R!⁆::Send("ᴙ")
:x:⁅-R?⁆::Send("ᴚ")
:x:⁅-R?!⁆::Send("ʁ")
:x:⁅-S⁆::Send("ꜱ")
:x:⁅-sh!⁆::Send("ʅ")
:x:⁅-T⁆::Send("ᴛ")
:x:⁅-U⁆::Send("ᴜ")
:x:⁅-Ʉ⁆::Send("ᵾ")
:x:⁅-V⁆::Send("ᴠ")
:x:⁅-W⁆::Send("ᴡ")
:x:⁅-Y⁆::Send("ʏ")
:x:⁅-Z⁆::Send("ᴢ")
:x:⁅-ZH⁆::Send("ᴣ")
:x:⁅+-(⁆::Send("Ꜥ")
:x:⁅-(⁆::Send("ꜥ")
:x:⁅-(>⁆::Send("ᴖ")
:x:⁅-)>⁆::Send("ᴗ")
:x:⁅-[[>⁆::Send("ʭ")
:x:⁅+-)-)⁆::Send("Ꜣ")
:x:⁅-)-)⁆::Send("ꜣ")
:x:⁅+:⁆::Send("˸")

; Superscripts
:x:⁅^A⁆::Send("ᴬ")
:x:⁅^a⁆::Send("ᵃ")
:x:⁅^a?⁆::Send("ᵄ")
:x:⁅^AA⁆::Send("𐞀")
:x:⁅^AE⁆::Send("ᴭ")
:x:⁅^ae⁆::Send("𐞃")
:x:⁅^ae?⁆::Send("ᵆ")
:x:⁅^ain⁆::Send("ᵜ")
:x:⁅^B⁆::Send("ᴮ")
:x:⁅^b⁆::Send("ᵇ")
:x:⁅^-B⁆::Send("𐞄")
:x:⁅^Ƀ⁆::Send("ᴯ")
:x:⁅^b'⁆::Send("𐞅")
:x:⁅^C⁆::Send("ꟲ")
:x:⁅^c⁆::Send("ᶜ")
:x:⁅^c?⁆::Send("ᵓ")
:x:⁅^D⁆::Send("ᴰ")
:x:⁅^d⁆::Send("ᵈ")
:x:⁅^d'⁆::Send("𐞌")
:x:⁅^dh⁆::Send("ᶞ")
:x:⁅^ɖ⁆::Send("𐞋")
:x:⁅^ɖ'⁆::Send("𐞍")
:x:⁅^dz⁆::Send("𐞇")
:x:⁅^dʐ⁆::Send("𐞈")
:x:⁅^dz,⁆::Send("𐞉")
:x:⁅^dzh⁆::Send("𐞊")
:x:⁅^E⁆::Send("ᴱ")
:x:⁅^e⁆::Send("ᵉ")
:x:⁅^E?⁆::Send("ᴲ")
:x:⁅^e?⁆::Send("ᵊ")
:x:⁅^E!⁆::Send("ᴲ")
:x:⁅^e!⁆::Send("𐞎")
:x:⁅^F⁆::Send("ꟳ")
:x:⁅^f⁆::Send("ᶠ")
:x:⁅^f?⁆::Send("ᶡ")
:x:⁅^f?'⁆::Send("𐞘")
:x:⁅^fng⁆::Send("𐞐")
:x:⁅^G⁆::Send("ᴳ")
:x:⁅^g⁆::Send("ᵍ")
:x:⁅^g'⁆::Send("𐞓")
:x:⁅^-G⁆::Send("𐞒")
:x:⁅^-G'⁆::Send("𐞔")
:x:⁅^H⁆::Send("ᴴ")
:x:⁅^h⁆::Send("ʰ")
:x:⁅^h?⁆::Send("ᶣ")
:x:⁅^Ħ⁆::Send("ꟸ")
:x:⁅^ħ⁆::Send("𐞕")
:x:⁅^h'⁆::Send("ʱ")
:x:⁅^hng⁆::Send("ꭜ")
:x:⁅^hng'⁆::Send("𐞗")
:x:⁅^-H⁆::Send("𐞖")
:x:⁅^I⁆::Send("ᴵ")
:x:⁅^i⁆::Send("ⁱ")
:x:⁅^i?⁆::Send("ᵎ")
:x:⁅^ɨ⁆::Send("ᶤ")
:x:⁅^-I⁆::Send("ᶦ")
:x:⁅^-Ɨ⁆::Send("ᶧ")
:x:⁅^J⁆::Send("ᴶ")
:x:⁅^j⁆::Send("ʲ")
:x:⁅^j;⁆::Send("ᶨ")
:x:⁅^j# ̵⁆::Send("ᶡ")
:x:⁅^j#' ̵⁆::Send("𐞘")
:x:⁅^K⁆::Send("ᴷ")
:x:⁅^k⁆::Send("ᵏ")
:x:⁅^L⁆::Send("ᴸ")
:x:⁅^l⁆::Send("ˡ")
:x:⁅^L<⁆::Send("ꜚ")
:x:⁅^ɭ⁆::Send("ᶩ")
:x:⁅^ls⁆::Send("𐞙")
:x:⁅^ls,⁆::Send("𐞡")
:x:⁅^LSH⁆::Send("𐞜")
:x:⁅^lsh⁆::Send("𐞛")
:x:⁅^lsh ̢⁆::Send("𐞝")
:x:⁅^lz⁆::Send("𐞚")
:x:⁅^lzh⁆::Send("𐞞")
:x:⁅^lzh ̢⁆::Send("𐞟")
:x:⁅^ᶅ⁆::Send("ᶪ")
:x:⁅^l~&⁆::Send("ꭝ")
:x:⁅^l~~⁆::Send("ꭞ")
:x:⁅^-L⁆::Send("ᶫ")
:x:⁅^M⁆::Send("ᴹ")
:x:⁅^m⁆::Send("ᵐ")
:x:⁅^m?⁆::Send("ᵚ")
:x:⁅^m?|⁆::Send("ᶭ")
:x:⁅^m'⁆::Send("ᶬ")
:x:⁅^mng⁆::Send("ᶬ")
:x:⁅^N⁆::Send("ᴺ")
:x:⁅^n⁆::Send("ⁿ")
:x:⁅^ɳ⁆::Send("ᶯ")
:x:⁅^N!⁆::Send("ᴻ")
:x:⁅^n'⁆::Send("ᶮ")
:x:⁅^ng⁆::Send("ᵑ")
:x:⁅^nj⁆::Send("ᶮ")
:x:⁅^-N⁆::Send("ᶰ")
:x:⁅^O⁆::Send("ᴼ")
:x:⁅^o⁆::Send("ᵒ")
:x:⁅^ø⁆::Send("𐞢")
:x:⁅^ɵ⁆::Send("ᶱ")
:x:⁅^OE⁆::Send("𐞣")
:x:⁅^oe⁆::Send("ꟹ")
:x:⁅^OU⁆::Send("ᴽ")
:x:⁅^O·⁆::Send("𐞵")
:x:⁅^P⁆::Send("ᴾ")
:x:⁅^p⁆::Send("ᵖ")
:x:⁅^ph⁆::Send("ᶲ")
:x:⁅^Q⁆::Send("ꟴ")
:x:⁅^q⁆::Send("𐞥")
:x:⁅^R⁆::Send("ᴿ")
:x:⁅^r⁆::Send("ʳ")
:x:⁅^r?⁆::Send("ʴ")
:x:⁅^r?'⁆::Send("ʵ")
:x:⁅^r?|⁆::Send("𐞦")
:x:⁅^r?|'⁆::Send("𐞧")
:x:⁅^r?~⁆::Send("ꭨ")
:x:⁅^r#⁆::Send("𐞩")
:x:⁅^r'⁆::Send("𐞨")
:x:⁅^ɽ⁆::Send("𐞨")
:x:⁅^-R⁆::Send("𐞪")
:x:⁅^-R?!⁆::Send("ʶ")
:x:⁅^s⁆::Send("ˢ")
:x:⁅^ʂ⁆::Send("ᶳ")
:x:⁅^s,⁆::Send("ᶝ")
:x:⁅^s,&⁆::Send("𐞺")
:x:⁅^sh⁆::Send("ᶴ")
:x:⁅^T⁆::Send("ᵀ")
:x:⁅^t⁆::Send("ᵗ")
:x:⁅^ts⁆::Send("𐞬")
:x:⁅^tʂ⁆::Send("𐞭")
:x:⁅^ts,⁆::Send("𐞫")
:x:⁅^tsh⁆::Send("𐞮")
:x:⁅^ʈ⁆::Send("𐞯")
:x:⁅^ƫ⁆::Send("ᶵ")
:x:⁅^U⁆::Send("ᵁ")
:x:⁅^u⁆::Send("ᵘ")
:x:⁅^ʉ⁆::Send("ᶶ")
:x:⁅^u'⁆::Send("ꭟ")
:x:⁅^u<⁆::Send("ᵙ")
:x:⁅^-U⁆::Send("ᶸ")
:x:⁅^us⁆::Send("ꝰ")
:x:⁅^V⁆::Send("ⱽ")
:x:⁅^v⁆::Send("ᵛ")
:x:⁅^v?⁆::Send("ᶺ")
:x:⁅^v'⁆::Send("𐞰")
:x:⁅^W⁆::Send("ᵂ")
:x:⁅^w⁆::Send("ʷ")
:x:⁅^w?⁆::Send("ꭩ")
:x:⁅^x⁆::Send("ˣ")
:x:⁅^y⁆::Send("ʸ")
:x:⁅^y?⁆::Send("𐞠")
:x:⁅^-Y⁆::Send("𐞲")
:x:⁅^z⁆::Send("ᶻ")
:x:⁅^ʐ⁆::Send("ᶼ")
:x:⁅^z,⁆::Send("ᶽ")
:x:⁅^zh⁆::Send("ᶾ")
:x:⁅^?#⁆::Send("ˀ")
:x:⁅^?# ̵⁆::Send("𐞳")
:x:⁅^?#!⁆::Send("ˤ")
:x:⁅^?#! ̵⁆::Send("𐞴")
:x:⁅^``a⁆::Send("ᵅ")
:x:⁅^``a?⁆::Send("ᶛ")
:x:⁅^``e⁆::Send("ᵋ")
:x:⁅^``e?⁆::Send("ᵌ")
:x:⁅^``e!⁆::Send("ᶟ")
:x:⁅^``eo!⁆::Send("𐞏")
:x:⁅^``b⁆::Send("ᵝ")
:x:⁅^``g⁆::Send("ˠ")
:x:⁅^``i⁆::Send("ᶥ")
:x:⁅^``ow⁆::Send("𐞤")
:x:⁅^``u⁆::Send("ᶷ")
:x:⁅^``v⁆::Send("ᶹ")
:x:⁅^``x⁆::Send("ᵡ")
:x:⁅^``y⁆::Send("𐞑")
:x:⁅^``|⁆::Send("𐞶")
:x:⁅^``|=⁆::Send("𐞸")
:x:⁅^``||⁆::Send("𐞷")
:x:⁅^``! ̢⁆::Send("𐞹")
:x:⁅^``:⁆::Send("𐞁")
:x:⁅^``;⁆::Send("𐞂")
:x:⁅^0⁆::Send("⁰")
:x:⁅^1⁆::Send("¹")
:x:⁅^2⁆::Send("²")
:x:⁅^3⁆::Send("³")
:x:⁅^4⁆::Send("⁴")
:x:⁅^5⁆::Send("⁵")
:x:⁅^6⁆::Send("⁶")
:x:⁅^7⁆::Send("⁷")
:x:⁅^8⁆::Send("⁸")
:x:⁅^9⁆::Send("⁹")
:x:⁅^+⁆::Send("⁺")
:x:⁅^-⁆::Send("⁻")
:x:⁅^=⁆::Send("⁼")
:x:⁅^(⁆::Send("⁽")
:x:⁅^)⁆::Send("⁾")
:x:⁅^!⁆::Send("ꜝ")
:x:⁅^!?⁆::Send("ꜞ")
:x:⁅^,⁆::Send("ʼ")
:x:⁅^,,⁆::Send("ˮ")
:x:⁅^,?⁆::Send("ʻ")
:x:⁅^,!⁆::Send("ʽ")
:x:⁅^-(⁆::Send("ʿ")
:x:⁅^-)⁆::Send("ʾ")
:x:⁅^-(>⁆::Send("ᵔ")
:x:⁅^-)>⁆::Send("ᵕ")

; Subscripts
:x:⁅_a⁆::Send("ₐ")
:x:⁅_e⁆::Send("ₑ")
:x:⁅_e?⁆::Send("ₔ")
:x:⁅_h⁆::Send("ₕ")
:x:⁅_i⁆::Send("ᵢ")
:x:⁅_j⁆::Send("ⱼ")
:x:⁅_k⁆::Send("ₖ")
:x:⁅_l⁆::Send("ₗ")
:x:⁅_m⁆::Send("ₘ")
:x:⁅_n⁆::Send("ₙ")
:x:⁅_o⁆::Send("ₒ")
:x:⁅_p⁆::Send("ₚ")
:x:⁅_r⁆::Send("ᵣ")
:x:⁅_s⁆::Send("ₛ")
:x:⁅_t⁆::Send("ₜ")
:x:⁅_u⁆::Send("ᵤ")
:x:⁅_v⁆::Send("ᵥ")
:x:⁅_x⁆::Send("ₓ")
:x:⁅_0⁆::Send("₀")
:x:⁅_1⁆::Send("₁")
:x:⁅_2⁆::Send("₂")
:x:⁅_3⁆::Send("₃")
:x:⁅_4⁆::Send("₄")
:x:⁅_5⁆::Send("₅")
:x:⁅_6⁆::Send("₆")
:x:⁅_7⁆::Send("₇")
:x:⁅_8⁆::Send("₈")
:x:⁅_9⁆::Send("₉")
:x:⁅_+⁆::Send("₊")
:x:⁅_-⁆::Send("₋")
:x:⁅_=⁆::Send("₌")
:x:⁅_(⁆::Send("₍")
:x:⁅_)⁆::Send("₎")
:x:⁅_]>⁆::Send("˽")
:x:⁅_L!>⁆::Send("˾")
:x:⁅_``<⁆::Send("˱")
:x:⁅_``>⁆::Send("˲")
:x:⁅_``^⁆::Send("˰")
:x:⁅_``^?⁆::Send("˯")
:x:⁅_``<-⁆::Send("˿")

; Middle Chinese Tone Markers
:x:⁅_U>⁆::Send("꜀")
:x:⁅_UI>⁆::Send("꜁")
:x:⁅^U>⁆::Send("꜂")
:x:⁅^UI>⁆::Send("꜃")
:x:⁅^U<⁆::Send("꜄")
:x:⁅^IU<⁆::Send("꜅")
:x:⁅_U<⁆::Send("꜆")
:x:⁅_IU<⁆::Send("꜇")

; Diacritics Above
:x:⁅*a⁆::Send("ͣ")
:x:⁅*ae⁆::Send("ᷔ")
:x:⁅*ao⁆::Send("ᷕ")
:x:⁅*av⁆::Send("ᷖ")
:x:⁅*ä⁆::Send("ᷲ")
:x:⁅*b⁆::Send("ᷨ")
:x:⁅*c⁆::Send("ͨ")
:x:⁅*ç⁆::Send("ᷗ")
:x:⁅*d⁆::Send("ͩ")
:x:⁅*dh⁆::Send("ᷙ")
:x:⁅*e⁆::Send("ͤ")
:x:⁅*e?⁆::Send("ᷪ")
:x:⁅*f⁆::Send("ᷫ")
:x:⁅*g⁆::Send("ᷚ")
:x:⁅*-G⁆::Send("ᷛ")
:x:⁅*h⁆::Send("ͪ")
:x:⁅*i⁆::Send("ͥ")
:x:⁅*k⁆::Send("ᷜ")
:x:⁅*l⁆::Send("ᷝ")
:x:⁅*l~~⁆::Send("ᷬ")
:x:⁅*L>!⁆::Send("̚")
:x:⁅*-L⁆::Send("ᷞ")
:x:⁅*m⁆::Send("ͫ")
:x:⁅*-M⁆::Send("ᷟ")
:x:⁅*n⁆::Send("ᷠ")
:x:⁅*-N⁆::Send("ᷡ")
:x:⁅*o⁆::Send("ͦ")
:x:⁅*ö⁆::Send("ᷳ")
:x:⁅*/o⁆::Send("ᷭ")
:x:⁅*p⁆::Send("ᷮ")
:x:⁅*r⁆::Send("ͬ")
:x:⁅*-R⁆::Send("ᷢ")
:x:⁅*s⁆::Send("ᷤ")
:x:⁅*sh⁆::Send("ᷯ")
:x:⁅*t⁆::Send("ͭ")
:x:⁅*T?⁆::Send("᷵")
:x:⁅*u⁆::Send("ͧ")
:x:⁅*ur⁆::Send("᷑")
:x:⁅*us⁆::Send("᷒")
:x:⁅*ü⁆::Send("ᷴ")
:x:⁅*/u⁆::Send("ᷰ")
:x:⁅*v⁆::Send("ͮ")
:x:⁅*w⁆::Send("ᷱ")
:x:⁅*x⁆::Send("ͯ")
:x:⁅*z⁆::Send("ᷦ")
:x:⁅*8>⁆::Send("᪲")
:x:⁅*``a⁆::Send("ᷧ")
:x:⁅*``b⁆::Send("ᷩ")
:x:⁅*``r⁆::Send("ᷣ")
:x:⁅*``s⁆::Send("ᷥ")
:x:⁅*,⁆::Send("̓")
:x:⁅*,&⁆::Send("̓")
:x:⁅*,?⁆::Send("̒")
:x:⁅*,!⁆::Send("̔")
:x:⁅* ,⁆::Send("̕")
:x:⁅*~!>⁆::Send("̾")
:x:⁅*~>!⁆::Send("̾")
:x:⁅*[>⁆::Send("͆")
:x:⁅*(⁆::Send("͑")
:x:⁅*)⁆::Send("͗")
:x:⁅*///⁆::Send("᷻")
:x:⁅*( )⁆::Send("᪻")
:x:⁅*(( ))⁆::Send("᪼")
:x:⁅*( ⁆::Send("᫁")
:x:⁅* )⁆::Send("᫂")
:x:⁅*[ ]⁆::Send("᫅")
:x:⁅*#⁆::Send("᫆")
:x:⁅*+⁆::Send("᫈")
:x:⁅*++⁆::Send("᫉")

; Overlay Diacritics
:x:⁅·~⁆::Send("̴")
:x:⁅·( )⁆::Send("᪾")

; Diacritics Below
:x:⁅.is⁆::Send("᷐")
:x:⁅.L>!⁆::Send("͉")
:x:⁅.r⁆::Send("᷊")
:x:⁅.T⁆::Send("̞")
:x:⁅.T?⁆::Send("̝")
:x:⁅.T<!⁆::Send("̘")
:x:⁅.T>!⁆::Send("̙")
:x:⁅.w⁆::Send("ᪿ")
:x:⁅.w?⁆::Send("ᫀ")
:x:⁅.``i⁆::Send("ͅ")
:x:⁅.=⁆::Send("͇")
:x:⁅.*⁆::Send("͙")
:x:⁅.(⁆::Send("̜")
:x:⁅.)⁆::Send("̹")
:x:⁅.-⁆::Send("̠")
:x:⁅.+⁆::Send("̟")
:x:⁅.++⁆::Send("᫊")
:x:⁅.[>⁆::Send("̪")
:x:⁅.]>⁆::Send("̺")
:x:⁅.[]>⁆::Send("̻")
:x:⁅.~~>⁆::Send("᷂")
:x:⁅./⁆::Send("᪹")
:x:⁅../⁆::Send("᪺")
:x:⁅.( )⁆::Send("᪽")
:x:⁅.( ⁆::Send("᫃")
:x:⁅. )⁆::Send("᫄")

; Compound Diacritics
:x:⁅̆̇⁆::Send("̐")
:x:⁅̇̑⁆::Send("͒")
:x:⁅̈́⁆::Send("̈́")
:x:⁅̃́⁆::Send("͊")
:x:⁅̇̃̇⁆::Send("͋")
:x:⁅̃̃⁆::Send("͌")
:x:⁅̅̅⁆::Send("̿")
:x:⁅̇̀̇⁆::Send("᷀")
:x:⁅̇́̇⁆::Send("᷁")
:x:⁅̆́⁆::Send("᷃")
:x:⁅̄́⁆::Send("᷄")
:x:⁅̀̄⁆::Send("᷅")
:x:⁅̀̄⁆::Send("᷆")
:x:⁅̄̀⁆::Send("᷆")
:x:⁅́̄⁆::Send("᷇")
:x:⁅̀́̀⁆::Send("᷈")
:x:⁅́̀́⁆::Send("᷉")
:x:⁅́̄́⁆::Send("͛")
:x:⁅̈̊⁆::Send("᪱")
:x:⁅̈̇⁆::Send("᪴")
:x:⁅̆̄⁆::Send("᷋")
:x:⁅̄̆⁆::Send("᷌")
:x:⁅̂̂⁆::Send("᪰")
:x:⁅̌̍⁆::Send("᪳")
:x:⁅̆̆⁆::Send("᫇")
:x:⁅́́́⁆::Send("᫋")

; Modified Diacritics
:x:⁅ ̇⁆::Send("͘")
:x:⁅̇ ⁆::Send("᷸")
:x:⁅ ̆⁆::Send("᷶")
:x:⁅̆ ⁆::Send("᷷")
:x:⁅̆|⁆::Send("͝")
:x:⁅̑|⁆::Send("͡")
:x:⁅̄|⁆::Send("͞")
:x:⁅̃|⁆::Send("͠")
:x:⁅̂|⁆::Send("᷍")
:x:⁅̂<⁆::Send("᷾")
:x:⁅̂>⁆::Send("͐")
:x:⁅̆̆&⁆::Send("ᷓ")

; Special Diacritics
:x:⁅̮̮⁆::Send("̫")
:x:⁅̯̯⁆::Send("̼")
:x:⁅̲̲⁆::Send("̳")
:x:⁅̥̥⁆::Send("͚")
:x:⁅̭̩⁆::Send("͎")
:x:⁅̰̰⁆::Send("᷽")
:x:⁅̖̲̗⁆::Send("᷹")
:x:⁅̯̯̯⁆::Send("᪶")
:x:⁅̗̱̗⁆::Send("᷏")
:x:⁅͓͓⁆::Send("᪵")

; Modified Special Diacritics
:x:⁅̣ ⁆::Send("᷺")
:x:⁅̮|⁆::Send("͜")
:x:⁅̯|⁆::Send("᷼")
:x:⁅̱|⁆::Send("͟")
:x:⁅̭<⁆::Send("͔")
:x:⁅̭>⁆::Send("͕")
:x:⁅̭>̭⁆::Send("͖")
:x:⁅̭>̬⁆::Send("᷿")
:x:⁅̭̩̬>⁆::Send("͍")
:x:⁅̩̩̬>⁆::Send("͢")
:x:⁅̨&⁆::Send("᪷")
:x:⁅̨̨&⁆::Send("᪸")

; Fullwidths
:x:⁅ A⁆::Send("Ａ")
:x:⁅ a⁆::Send("ａ")
:x:⁅ B⁆::Send("Ｂ")
:x:⁅ b⁆::Send("ｂ")
:x:⁅ C⁆::Send("Ｃ")
:x:⁅ c⁆::Send("ｃ")
:x:⁅ D⁆::Send("Ｄ")
:x:⁅ d⁆::Send("ｄ")
:x:⁅ E⁆::Send("Ｅ")
:x:⁅ e⁆::Send("ｅ")
:x:⁅ F⁆::Send("Ｆ")
:x:⁅ f⁆::Send("ｆ")
:x:⁅ G⁆::Send("Ｇ")
:x:⁅ g⁆::Send("ｇ")
:x:⁅ H⁆::Send("Ｈ")
:x:⁅ h⁆::Send("ｈ")
:x:⁅ I⁆::Send("Ｉ")
:x:⁅ i⁆::Send("ｉ")
:x:⁅ J⁆::Send("Ｊ")
:x:⁅ j⁆::Send("ｊ")
:x:⁅ K⁆::Send("Ｋ")
:x:⁅ k⁆::Send("ｋ")
:x:⁅ L⁆::Send("Ｌ")
:x:⁅ l⁆::Send("ｋ")
:x:⁅ M⁆::Send("Ｍ")
:x:⁅ m⁆::Send("ｍ")
:x:⁅ N⁆::Send("Ｎ")
:x:⁅ n⁆::Send("ｎ")
:x:⁅ O⁆::Send("Ｏ")
:x:⁅ o⁆::Send("ｏ")
:x:⁅ P⁆::Send("Ｐ")
:x:⁅ p⁆::Send("ｐ")
:x:⁅ Q⁆::Send("Ｑ")
:x:⁅ q⁆::Send("ｑ")
:x:⁅ R⁆::Send("Ｒ")
:x:⁅ r⁆::Send("ｒ")
:x:⁅ S⁆::Send("Ｓ")
:x:⁅ s⁆::Send("ｓ")
:x:⁅ T⁆::Send("Ｔ")
:x:⁅ t⁆::Send("ｔ")
:x:⁅ U⁆::Send("Ｕ")
:x:⁅ u⁆::Send("ｕ")
:x:⁅ V⁆::Send("Ｖ")
:x:⁅ v⁆::Send("ｖ")
:x:⁅ W⁆::Send("Ｗ")
:x:⁅ w⁆::Send("ｗ")
:x:⁅ X⁆::Send("Ｘ")
:x:⁅ x⁆::Send("ｘ")
:x:⁅ Y⁆::Send("Ｙ")
:x:⁅ y⁆::Send("ｙ")
:x:⁅ Z⁆::Send("Ｚ")
:x:⁅ z⁆::Send("ｚ")
:x:⁅ [⁆::Send("［")
:x:⁅ {⁆::Send("｛")
:x:⁅ \⁆::Send("＼")
:x:⁅ |⁆::Send("｜")
:x:⁅ ]⁆::Send("］")
:x:⁅ }⁆::Send("｝")
:x:⁅ ^⁆::Send("＾")
:x:⁅ ~⁆::Send("～")
:x:⁅ _⁆::Send("＿")
:x:⁅ (⁆::Send("｟")
:x:⁅ )⁆::Send("｠")
:x:⁅ @⁆::Send("＠")
:x:⁅ ``⁆::Send("｀")

; Additional Ligatures
:x:⁅=DZ⁆::Send("Ǳ")
:x:⁅=Dz⁆::Send("ǲ")
:x:⁅=dz⁆::Send("ǳ")
:x:⁅=DŽ⁆::Send("Ǆ")
:x:⁅=Dž⁆::Send("ǅ")
:x:⁅=dž⁆::Send("ǆ")
:x:⁅=IJ⁆::Send("Ĳ")
:x:⁅=ij⁆::Send("ĳ")
:x:⁅=LJ⁆::Send("Ǉ")
:x:⁅=Lj⁆::Send("ǈ")
:x:⁅=lj⁆::Send("ǉ")
:x:⁅=NJ⁆::Send("Ǌ")
:x:⁅=Nj⁆::Send("ǋ")
:x:⁅=nj⁆::Send("ǌ")
:x:⁅=th/⁆::Send("ᵺ")

; Standalone Diacritics
:x:⁅=̈⁆::Send("¨")
:x:⁅=̄⁆::Send("¯")
:x:⁅=́⁆::Send("´")
:x:⁅=̧⁆::Send("¸")
:x:⁅=̌⁆::Send("ˇ")
:x:⁅=̆⁆::Send("˘")
:x:⁅=̇⁆::Send("˙")
:x:⁅=̊⁆::Send("˚")
:x:⁅=̨⁆::Send("˛")
:x:⁅=̃⁆::Send("˜")
:x:⁅=̋⁆::Send("˝")
:x:⁅=̅⁆::Send("‾")
:x:⁅=̲̲⁆::Send("‗")
:x:⁅='⁆::Send("′")
:x:⁅=''⁆::Send("″")
:x:⁅='''⁆::Send("‴")
:x:⁅=''''⁆::Send("⁗")
:x:⁅='!⁆::Send("‵")
:x:⁅=''!⁆::Send("‶")
:x:⁅='''!⁆::Send("‷")
:x:⁅=̑|⁆::Send("⁀")
:x:⁅=̮̑|⁆::Send("⁐")
:x:⁅=̮|⁆::Send("‿")
:x:⁅=̯|⁆::Send("⁔")

; Modifiers
:x:⁅~̂⁆::Send("ˆ")
:x:⁅~̭⁆::Send("ꞈ")
:x:⁅~̬⁆::Send("ˬ")
:x:⁅~̑̆⁆::Send("꭛")
:x:⁅~̍⁆::Send("ˈ")
:x:⁅~̩⁆::Send("ˌ")
:x:⁅~̄⁆::Send("ˉ")
:x:⁅~̱⁆::Send("ˍ")
:x:⁅~́⁆::Send("ˊ")
:x:⁅~̗⁆::Send("ˏ")
:x:⁅~̀⁆::Send("ˋ")
:x:⁅~̖⁆::Send("ˎ")
:x:⁅~̽⁆::Send("˟")
:x:⁅~̿⁆::Send("˭")
:x:⁅~̥⁆::Send("˳")
:x:⁅~̰⁆::Send("˷")
:x:⁅~̍̂⁆::Send("ꜛ")
:x:⁅~̌̍⁆::Send("ꜜ")
:x:⁅~̇̍⁆::Send("ꜗ")
:x:⁅~̇́⁆::Send("ꜘ")
:x:⁅~̄̇⁆::Send("ꜙ")
:x:⁅~r⁆::Send("˞")
:x:⁅~'⁆::Send("ʹ")
:x:⁅~''⁆::Send("ʺ")

; Centered Modifiers
:x:⁅%T⁆::Send("˕")
:x:⁅%T?⁆::Send("˔")
:x:⁅%T<!⁆::Send("꭪")
:x:⁅%T>!⁆::Send("꭫")
:x:⁅%!?⁆::Send("ꜟ")
:x:⁅%+⁆::Send("˖")
:x:⁅%-⁆::Send("˗")
:x:⁅%(⁆::Send("˓")
:x:⁅%)⁆::Send("˒")
:x:⁅% ̀⁆::Send("˴")
:x:⁅% ̏⁆::Send("˵")
:x:⁅% ̋⁆::Send("˶")

; Anglicana
:x:⁅ang:W⁆::Send("Ꟃ")
:x:⁅ang:w⁆::Send("ꟃ")

; Blackletter
:x:⁅bl:e⁆::Send("ꬲ")
:x:⁅bl:o⁆::Send("ꬽ")
:x:⁅bl:ø⁆::Send("ꬾ")

; Dashes
:x:⁅ds:b⁆::Send("―")
:x:⁅ds:f⁆::Send("‒")
:x:⁅ds:m⁆::Send("—")
:x:⁅ds:n⁆::Send("–")

; Greek
:x:⁅g:A⁆::Send("Α")
:x:⁅g:a⁆::Send("α")
:x:⁅g:B⁆::Send("Β")
:x:⁅g:b⁆::Send("β")
:x:⁅g:G⁆::Send("Γ")
:x:⁅g:g⁆::Send("Γ")
:x:⁅g:D⁆::Send("δ")
:x:⁅g:d⁆::Send("δ")
:x:⁅g:E⁆::Send("ε")
:x:⁅g:e⁆::Send("ε")
:x:⁅g:Z⁆::Send("Ζ")
:x:⁅g:z⁆::Send("ζ")
:x:⁅g:H⁆::Send("Η")
:x:⁅g:h⁆::Send("η")
:x:⁅g:TH⁆::Send("Θ")
:x:⁅g:th⁆::Send("θ")
:x:⁅g:I⁆::Send("Ι")
:x:⁅g:i⁆::Send("ι")
:x:⁅g:K⁆::Send("Κ")
:x:⁅g:k⁆::Send("κ")
:x:⁅g:L⁆::Send("Λ")
:x:⁅g:l⁆::Send("λ")
:x:⁅g:M⁆::Send("Μ")
:x:⁅g:m⁆::Send("μ")
:x:⁅g:N⁆::Send("Ν")
:x:⁅g:n⁆::Send("ν")
:x:⁅g:X⁆::Send("Ξ")
:x:⁅g:x⁆::Send("ξ")
:x:⁅g:KS⁆::Send("Ξ")
:x:⁅g:ks⁆::Send("ξ")
:x:⁅g:O⁆::Send("Ο")
:x:⁅g:o⁆::Send("ο")
:x:⁅g:P⁆::Send("Π")
:x:⁅g:p⁆::Send("π")
:x:⁅g:R⁆::Send("Ρ")
:x:⁅g:r⁆::Send("ρ")
:x:⁅g:RH⁆::Send("Ρ")
:x:⁅g:rh⁆::Send("ρ")
:x:⁅g:S⁆::Send("Σ")
:x:⁅g:s⁆::Send("σ")
:x:⁅g:s&⁆::Send("ς")
:x:⁅g:T⁆::Send("Τ")
:x:⁅g:t⁆::Send("τ")
:x:⁅g:U⁆::Send("Υ")
:x:⁅g:u⁆::Send("υ")
:x:⁅g:Y⁆::Send("Υ")
:x:⁅g:y⁆::Send("υ")
:x:⁅g:F⁆::Send("Φ")
:x:⁅g:f⁆::Send("φ")
:x:⁅g:PH⁆::Send("Φ")
:x:⁅g:ph⁆::Send("φ")
:x:⁅g:CH⁆::Send("Χ")
:x:⁅g:ch⁆::Send("χ")
:x:⁅g:KH⁆::Send("Χ")
:x:⁅g:kh⁆::Send("χ")
:x:⁅g:PS⁆::Send("Ψ")
:x:⁅g:ps⁆::Send("ψ")
:x:⁅g:OO⁆::Send("Ω")
:x:⁅g:oo⁆::Send("ω")
:x:⁅g:-G⁆::Send("ᴦ")
:x:⁅g:-L⁆::Send("ᴧ")
:x:⁅g:-P⁆::Send("ᴨ")
:x:⁅g:-R⁆::Send("ᴩ")
:x:⁅g:-PS⁆::Send("ᴪ")
:x:⁅g:-OO⁆::Send("ꭥ")
:x:⁅g:^b⁆::Send("ᵝ")
:x:⁅g:^g⁆::Send("ᵞ")
:x:⁅g:^d⁆::Send("ᵟ")
:x:⁅g:^e⁆::Send("ᵋ")
:x:⁅g:^th⁆::Send("ᶿ")
:x:⁅g:^i⁆::Send("ᶥ")
:x:⁅g:^ph⁆::Send("ᵠ")
:x:⁅g:^ch⁆::Send("ᵡ")
:x:⁅g:_b⁆::Send("ᵦ")
:x:⁅g:_g⁆::Send("ᵧ")
:x:⁅g:_i⁆::Send("ͺ")
:x:⁅g:_r⁆::Send("ᵨ")
:x:⁅g:_ph⁆::Send("ᵩ")
:x:⁅g:_ch⁆::Send("ᵪ")
:x:⁅g:.i⁆::Send("ͅ")
:x:⁅g:.oo⁆::Send("̫")

; Insular
:x:⁅i:D⁆::Send("Ꝺ")
:x:⁅i:d⁆::Send("ꝺ")
:x:⁅i:ET⁆::Send("⹒")
:x:⁅i:et⁆::Send("⁊")
:x:⁅i:F⁆::Send("Ꝼ")
:x:⁅i:f⁆::Send("ꝼ")
:x:⁅i:G⁆::Send("Ᵹ")
:x:⁅i:g⁆::Send("ᵹ")
:x:⁅i:G?⁆::Send("Ꝿ")
:x:⁅i:g?⁆::Send("ꝿ")
:x:⁅i:GO⁆::Send("Ꟑ")
:x:⁅i:go⁆::Send("ꟑ")
:x:⁅i:R⁆::Send("Ꞃ")
:x:⁅i:r⁆::Send("ꞃ")
:x:⁅i:S⁆::Send("Ꞅ")
:x:⁅i:s⁆::Send("ꞅ")
:x:⁅i:T⁆::Send("Ꞇ")
:x:⁅i:t⁆::Send("ꞇ")
:x:⁅i:*d⁆::Send("ᷘ")
:x:⁅i:*g⁆::Send("ᫌ")
:x:⁅i:*r⁆::Send("ᫍ")
:x:⁅i:*t⁆::Send("ᫎ")

; Mayan
:x:⁅ma:+3⁆::Send("Ꜫ")
:x:⁅ma:3⁆::Send("ꜫ")
:x:⁅ma:+4⁆::Send("Ꜭ")
:x:⁅ma:4⁆::Send("ꜭ")
:x:⁅ma:+4,⁆::Send("Ꜯ")
:x:⁅ma:4,⁆::Send("ꜯ")

; Middle Scots
:x:⁅ms:S⁆::Send("Ꟗ")
:x:⁅ms:s⁆::Send("ꟗ")
:x:⁅ms:SS⁆::Send("Ꟙ")
:x:⁅ms:ss⁆::Send("ꟙ")

; Middle Welsh
:x:⁅mw:LL⁆::Send("Ỻ")
:x:⁅mw:ll⁆::Send("ỻ")
:x:⁅mw:V⁆::Send("Ỽ")
:x:⁅mw:v⁆::Send("ỽ")
:x:⁅mw:Y⁆::Send("Ỿ")
:x:⁅mw:y⁆::Send("ỿ")

; Old English
:x:⁅oe:W⁆::Send("Ƿ")
:x:⁅oe:w⁆::Send("ƿ")
:x:⁅oe:ww⁆::Send("ꟕ")
:x:⁅oe:Y⁆::Send("Ȝ")
:x:⁅oe:y⁆::Send("ȝ")

; Old Norse
:x:⁅on:V⁆::Send("Ꝩ")
:x:⁅on:v⁆::Send("ꝩ")

; Old Polish
:x:⁅op:O⁆::Send("Ꟁ")
:x:⁅op:o⁆::Send("ꟁ")

; Roman Numerals
:x:⁅rn:I⁆::Send("Ⅰ")
:x:⁅rn:II⁆::Send("Ⅱ")
:x:⁅rn:III⁆::Send("Ⅲ")
:x:⁅rn:IV⁆::Send("Ⅳ")
:x:⁅rn:V⁆::Send("Ⅴ")
:x:⁅rn:VI⁆::Send("Ⅵ")
:x:⁅rn:VII⁆::Send("Ⅶ")
:x:⁅rn:VIII⁆::Send("Ⅷ")
:x:⁅rn:IX⁆::Send("Ⅸ")
:x:⁅rn:X⁆::Send("Ⅹ")
:x:⁅rn:XI⁆::Send("Ⅺ")
:x:⁅rn:XII⁆::Send("Ⅻ")
:x:⁅rn:L⁆::Send("Ⅼ")
:x:⁅rn:C⁆::Send("Ⅽ")
:x:⁅rn:D⁆::Send("Ⅾ")
:x:⁅rn:M⁆::Send("Ⅿ")
:x:⁅rn:i⁆::Send("ⅰ")
:x:⁅rn:ii⁆::Send("ⅱ")
:x:⁅rn:iii⁆::Send("ⅲ")
:x:⁅rn:iv⁆::Send("ⅳ")
:x:⁅rn:v⁆::Send("ⅴ")
:x:⁅rn:vi⁆::Send("ⅵ")
:x:⁅rn:vii⁆::Send("ⅶ")
:x:⁅rn:viii⁆::Send("ⅷ")
:x:⁅rn:ix⁆::Send("ⅸ")
:x:⁅rn:x⁆::Send("ⅹ")
:x:⁅rn:xi⁆::Send("ⅺ")
:x:⁅rn:xii⁆::Send("ⅻ")
:x:⁅rn:l⁆::Send("ⅼ")
:x:⁅rn:c⁆::Send("ⅽ")
:x:⁅rn:d⁆::Send("ⅾ")
:x:⁅rn:m⁆::Send("ⅿ")
:x:⁅rn:DD⁆::Send("ↀ")
:x:⁅rn:X*D⁆::Send("ↁ")
:x:⁅rn:XX*D⁆::Send("ↂ")
:x:⁅rn:C*D⁆::Send("ↇ")
:x:⁅rn:CC*D⁆::Send("ↈ")
:x:⁅rn:G⁆::Send("ↅ")
:x:⁅rn:Y⁆::Send("ↆ")

; Swedish Dialect Alphabet
:x:⁅sw:e⁆::Send("ⱸ")
:x:⁅sw:o⁆::Send("ⱺ")

; Tone Markers
:x:⁅t:gr⁆::Send("↗︎")
:x:⁅t:gf⁆::Send("↘︎")
:x:⁅t:5⁆::Send("˥")
:x:⁅t:4⁆::Send("˦")
:x:⁅t:3⁆::Send("˧")
:x:⁅t:2⁆::Send("˨")
:x:⁅t:1⁆::Send("˩")
:x:⁅t:|5⁆::Send("꜒")
:x:⁅t:|4⁆::Send("꜓")
:x:⁅t:|3⁆::Send("꜔")
:x:⁅t:|2⁆::Send("꜕")
:x:⁅t:|1⁆::Send("꜖")
:x:⁅t:5.⁆::Send("꜈")
:x:⁅t:4.⁆::Send("꜉")
:x:⁅t:3.⁆::Send("꜊")
:x:⁅t:2.⁆::Send("꜋")
:x:⁅t:1.⁆::Send("꜌")
:x:⁅t:|5.⁆::Send("꜍")
:x:⁅t:|4.⁆::Send("꜎")
:x:⁅t:|3.⁆::Send("꜏")
:x:⁅t:|2.⁆::Send("꜐")
:x:⁅t:|1.⁆::Send("꜑")
:x:⁅t:^(⁆::Send("˹")
:x:⁅t:^)⁆::Send("˺")
:x:⁅t:_(⁆::Send("˻")
:x:⁅t:_)⁆::Send("˼")
:x:⁅t:^( ̍⁆::Send("꜠")
:x:⁅t:_( ̩⁆::Send("꜡")

; Teuthonista
:x:⁅tt:r⁆::Send("ꭇ")
:x:⁅tt:r?⁆::Send("ꭋ")
:x:⁅tt:r?@⁆::Send("ꭌ")
:x:⁅tt:r!⁆::Send("ꭅ")
:x:⁅tt:-R⁆::Send("ꭆ")
:x:⁅tt:u⁆::Send("ꭎ")
:x:⁅tt:ʉ⁆::Send("ꭏ")
:x:⁅tt:x⁆::Send("ꭗ")
:x:⁅tt:x@⁆::Send("ꭘ")
:x:⁅tt:,x⁆::Send("ꭙ")
:x:⁅tt:,``x⁆::Send("ꭕ")
:x:⁅tt:y⁆::Send("ꭚ")

; Taiwanese Phonetic Symbols
:x:⁅tw:3⁆::Send("˪")
:x:⁅tw:7⁆::Send("˫")

; Volapük
:x:⁅vp:Ä⁆::Send("Ꞛ")
:x:⁅vp:ä⁆::Send("ꞛ")
:x:⁅vp:Ö⁆::Send("Ꞝ")
:x:⁅vp:ö⁆::Send("ꞝ")
:x:⁅vp:Ü⁆::Send("Ꞟ")
:x:⁅vp:ü⁆::Send("ꞟ")

; Yakut
:x:⁅yk:ib⁆::Send("ꭠ")
:x:⁅yk:ie⁆::Send("ꭡ")

; Zhuang
:x:⁅zw:MB⁆::Send("Ƃ")
:x:⁅zw:mb⁆::Send("ƃ")
:x:⁅zw:ND⁆::Send("Ƌ")
:x:⁅zw:nd⁆::Send("ƌ")
:x:⁅zw:+2⁆::Send("Ƨ")
:x:⁅zw:2⁆::Send("ƨ")
:x:⁅zw:+5⁆::Send("Ƽ")
:x:⁅zw:5⁆::Send("ƽ")
:x:⁅zw:+6⁆::Send("Ƅ")
:x:⁅zw:6⁆::Send("ƅ")

; Miscellaneous Symbols
:x:⁅CGJ⁆::Send("͏")
:x:⁅'⁆::Send("ʻ")
:x:⁅:⁆::Send("꞉")
:x:⁅=⁆::Send("꞊")
:x:⁅!⁆::Send("¡")
:x:⁅ox⁆::Send("¤")
:x:⁅|⁆::Send("¦")
:x:⁅ss⁆::Send("§")
:x:⁅@C⁆::Send("©")
:x:⁅^a_⁆::Send("ª")
:x:⁅<<⁆::Send("«")
:x:⁅NOT⁆::Send("¬")
:x:⁅(-)⁆::Send("­")
:x:⁅@R⁆::Send("®")
:x:⁅^o&⁆::Send("°")
:x:⁅+-⁆::Send("±")
:x:⁅P⁆::Send("¶")
:x:⁅.⁆::Send("·")
:x:⁅^o_⁆::Send("º")
:x:⁅>>⁆::Send("»")
:x:⁅?⁆::Send("¿")
:x:⁅MUL⁆::Send("×")
:x:⁅DIV⁆::Send("÷")
:x:⁅&⁆::Send("⅋")
:x:⁅TM⁆::Send("™")
:x:⁅@⁆::Send("◌")

; Currency Symbols
:x:⁅$c⁆::Send("¢")
:x:⁅$E⁆::Send("€")
:x:⁅$L⁆::Send("£")
:x:⁅$L&⁆::Send("₺")
:x:⁅$P⁆::Send("₽")
:x:⁅$P&⁆::Send("₱")
:x:⁅$R⁆::Send("₹")
:x:⁅$W⁆::Send("₩")
:x:⁅$Y⁆::Send("¥")

; Fractions
:x:⁅1/4⁆::Send("¼")
:x:⁅1/2⁆::Send("½")
:x:⁅3/4⁆::Send("¾")
:x:⁅1/7⁆::Send("⅐")
:x:⁅1/9⁆::Send("⅑")
:x:⁅1/10⁆::Send("⅒")
:x:⁅1/3⁆::Send("⅓")
:x:⁅2/3⁆::Send("⅔")
:x:⁅1/5⁆::Send("⅕")
:x:⁅2/5⁆::Send("⅖")
:x:⁅3/5⁆::Send("⅗")
:x:⁅4/5⁆::Send("⅘")
:x:⁅1/6⁆::Send("⅙")
:x:⁅5/6⁆::Send("⅚")
:x:⁅1/8⁆::Send("⅛")
:x:⁅3/8⁆::Send("⅜")
:x:⁅5/8⁆::Send("⅝")
:x:⁅7/8⁆::Send("⅞")
:x:⁅1/ ⁆::Send("⅟")
:x:⁅0/3⁆::Send("↉")
:x:⁅0/00⁆::Send("‰")
:x:⁅0/000⁆::Send("‱")
:x:⁅/⁆::Send("⁄")

/**********************************
 * ADDITIONAL DIACRITIC COMBINERS *
 **********************************/

#InputLevel 0

:x:a͗::Send("ẚ")
